---
title: "Week 2 Notes"
date: "2025-09-15"
---

[**Algorithmic Decision Making & Census Data**]{.underline}

[Inputs:]{.underline} Synonyms: Independent variables, “x”’s, predictors, features

[Outputs:]{.underline} Synonyms: dependent variable

*Government*

-            Idea is that using data will result in more consistent and unbiased output

-            Reasons for use: Efficiency, consistency , objectivity, cost savings

1)       Data Science

2)       Data Analytics (MUSA)

3)       Machine Learning 

4)       AI

**Subjectiveness**

-            Data cleaning decisions

-            Data coding or classification

-            Collection

-            How you interpret results

-            What variables you use

**Census Data Foundations**

·       9 basic questions (age, race, sex, etc.)

·       **Everyone** counted every 10 years

·       Constitutional requirement

·       Determines political representation

**American Community Survey (ACS)**

·       **3% of households** surveyed annually

·       detailed questions (income, education, housing costs, etc)

o   replacement of the same “long form” in 2005

·       Areas: of only 65,000 people.

·       Pretty small sample but you get them every year. Only aggregate level

·       **5-year estimates**

o   Take all 1-year and combine together including census tracts (1500-1800 people). Most accurate we can get at the smallest geography and we consider them a neighborhood.

§  It is changed for redistricting

§  Frustrating for us when redistricting happens

o   Most reliable data, largest sample

**Tidycensus**

-            This package helps organize the census data
