---
title: "Week-4-notes"
date: 2025-9-15
---

**Simple Features**
- Simple features - you can have multiple shapes on one row. For example, Hawaii which is multiple columns could be one row of data

- you can add column for geom information in the table. 

**Coordinate Reference Systems**
- Making a geographic coordinate system 

Step 1: *approximate earth's shape with an ellipsoid - there are lots of ellipsoid*

Step 2: *Tie ellipsoid to the real earth (datum)*
        Example --> Clarke's meade's ranch. North American datum of            1927. Also known as NAD 27. 
        also NAD 83 then WS84 are the earth centered instead 
        
        - All of these are known as geographical earth systems 
        
        -they are all flat lat/long systems on the 3 dimensional                elispse
      
Step 3: *Put down you Lat/Long grid on the elipsiod*

Step 4: *Project 3D coordinates on computer screen* 

-common type is cylindarical projection. if you wrap the earth in an ellipsoid, only the middle is touching the cylinder (line of tangency). Mercator is a famous example 

-the farther away places on the eart are away from the line of tangency in the middle the more distored it is --> good for preserving lattitudal shapes 

-transverse cylindrical --> would be cylinder vertically around the earth and good for preserving longitudal shapes (chile)

- conic -> could be good for long countries on the top of the earth (US / China / Russia)

**Best way of projeting** 
Projected Coordinate System (this is still starting from an ellipsoid and is then projected using conic or any of the above
1) UTM --> thin zones 
2) State plane --> PA --> uses conic projection 

In R you have to look up the code of the projected coordinate system. all these systems are based on some sort of Datum like NAD 83 

look up geographic coordinate sysmte vs projected coordinate system 

for quiz look into path of despair ... defining the projection and you need to tell it what it's in 

do in class practice 



