project:
  type: website
  output-dir: docs

website:
  title: "Sam Sen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: Labs
        menu:
          - href: Labs/Lab 0/Scripts/lab0_template.html
            text: Lab 0
            
      - text: Assignments 
        menu:
          - href: Assignments/Assignment_1/assignment_1.html
            text: Assignment 1
          - href: Assignments/Assignment_2/Sen_Sam_Assignment2.html
            text: Assignment 2

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

