<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sam Sen">
<meta name="dcterms.date" content="2025-11-30">

<title>Assignment 2: Spatial Analysis and Visualization – Sam Sen - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sam Sen - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../Labs/Lab 0/Scripts/lab0_template.html">
 <span class="dropdown-text">Lab 0</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_1/assignment_1.html">
 <span class="dropdown-text">Assignment 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_2/Sen_Sam_Assignment2.html">
 <span class="dropdown-text">Assignment 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_4/Assignment4_Sen_Sam.html">
 <span class="dropdown-text">Assignment 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_5/Assignment5_Sen_Sam.html">
 <span class="dropdown-text">Assignment 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-04-notes.html">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-05-notes.html">
 <span class="dropdown-text">Week 5</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a></li>
  <li><a href="#part-1-healthcare-access-for-vulnerable-populations" id="toc-part-1-healthcare-access-for-vulnerable-populations" class="nav-link" data-scroll-target="#part-1-healthcare-access-for-vulnerable-populations">Part 1: Healthcare Access for Vulnerable Populations</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#required-analysis-steps" id="toc-required-analysis-steps" class="nav-link" data-scroll-target="#required-analysis-steps">Required Analysis Steps</a></li>
  </ul></li>
  <li><a href="#load-spatial-data" id="toc-load-spatial-data" class="nav-link" data-scroll-target="#load-spatial-data">Load spatial data</a></li>
  <li><a href="#check-that-all-data-loaded-correctly" id="toc-check-that-all-data-loaded-correctly" class="nav-link" data-scroll-target="#check-that-all-data-loaded-correctly">Check that all data loaded correctly</a></li>
  <li><a href="#aggregate-statistics-by-county" id="toc-aggregate-statistics-by-county" class="nav-link" data-scroll-target="#aggregate-statistics-by-county">Aggregate statistics by county</a>
  <ul class="collapse">
  <li><a href="#part-2-comprehensive-visualization" id="toc-part-2-comprehensive-visualization" class="nav-link" data-scroll-target="#part-2-comprehensive-visualization">Part 2: Comprehensive Visualization</a>
  <ul class="collapse">
  <li><a href="#map-1-county-level-choropleth" id="toc-map-1-county-level-choropleth" class="nav-link" data-scroll-target="#map-1-county-level-choropleth">Map 1: County-Level Choropleth</a></li>
  <li><a href="#map-2-detailed-vulnerability-map" id="toc-map-2-detailed-vulnerability-map" class="nav-link" data-scroll-target="#map-2-detailed-vulnerability-map">Map 2: Detailed Vulnerability Map</a></li>
  <li><a href="#chart-distribution-analysis" id="toc-chart-distribution-analysis" class="nav-link" data-scroll-target="#chart-distribution-analysis">Chart: Distribution Analysis</a></li>
  </ul></li>
  <li><a href="#part-3-bring-your-own-data-analysis" id="toc-part-3-bring-your-own-data-analysis" class="nav-link" data-scroll-target="#part-3-bring-your-own-data-analysis">Part 3: Bring Your Own Data Analysis</a>
  <ul class="collapse">
  <li><a href="#challenge-options" id="toc-challenge-options" class="nav-link" data-scroll-target="#challenge-options">Challenge Options</a></li>
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a></li>
  <li><a href="#recommended-starting-points" id="toc-recommended-starting-points" class="nav-link" data-scroll-target="#recommended-starting-points">Recommended Starting Points</a></li>
  <li><a href="#your-analysis" id="toc-your-analysis" class="nav-link" data-scroll-target="#your-analysis">Your Analysis</a></li>
  </ul></li>
  <li><a href="#finally---a-few-comments-about-your-incorporation-of-feedback" id="toc-finally---a-few-comments-about-your-incorporation-of-feedback" class="nav-link" data-scroll-target="#finally---a-few-comments-about-your-incorporation-of-feedback">Finally - A few comments about your incorporation of feedback!</a></li>
  <li><a href="#submission-requirements" id="toc-submission-requirements" class="nav-link" data-scroll-target="#submission-requirements">Submission Requirements</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 2: Spatial Analysis and Visualization</h1>
<p class="subtitle lead">Healthcare Access and Equity in Pennsylvania</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sam Sen </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 30, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add this near the top of your .qmd after loading libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_progress =</span> <span class="cn">FALSE</span>)  <span class="co"># Suppress tigris progress bars</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_quiet =</span> <span class="cn">TRUE</span>)      <span class="co"># Additional quiet option</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="assignment-overview" class="level2">
<h2 class="anchored" data-anchor-id="assignment-overview">Assignment Overview</h2>
<p><strong>Learning Objectives:</strong> - Apply spatial operations to answer policy-relevant research questions - Integrate census demographic data with spatial analysis - Create publication-quality visualizations and maps - Work with spatial data from multiple sources - Communicate findings effectively for policy audiences</p>
<hr>
</section>
<section id="part-1-healthcare-access-for-vulnerable-populations" class="level2">
<h2 class="anchored" data-anchor-id="part-1-healthcare-access-for-vulnerable-populations">Part 1: Healthcare Access for Vulnerable Populations</h2>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">Research Question</h3>
<p><strong>Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?</strong></p>
<p>Your analysis should identify counties that should be priorities for healthcare investment and policy intervention.</p>
</section>
<section id="required-analysis-steps" class="level3">
<h3 class="anchored" data-anchor-id="required-analysis-steps">Required Analysis Steps</h3>
<p>Complete the following analysis, documenting each step with code and brief explanations:</p>
<section id="step-1-data-collection-5-points" class="level4">
<h4 class="anchored" data-anchor-id="step-1-data-collection-5-points">Step 1: Data Collection (5 points)</h4>
<p>Load the required spatial data: - Pennsylvania county boundaries - Pennsylvania hospitals (from lecture data) - Pennsylvania census tracts</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)    </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)           </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)   </span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)       </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
</section>
<section id="load-spatial-data" class="level1">
<h1>Load spatial data</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pennsylvania county boundaries</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pa_counties <span class="ot">&lt;-</span> <span class="fu">counties</span>(<span class="at">state =</span> <span class="st">"PA"</span>, <span class="at">cb =</span> <span class="cn">TRUE</span>, <span class="at">year =</span> <span class="dv">2022</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pennsylvania hospitals (from lecture data)</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>hospitals <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/hospitals.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `hospitals' from data source 
  `C:\Users\16468\OneDrive - PennO365\Documents\Academics\MUSA\Public_Policy_Analytics\portfolio-setup-ssen-droid\Assignments\Assignment_2\data\hospitals.geojson' 
  using driver `GeoJSON'
Simple feature collection with 223 features and 11 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pennsylvania census tracts</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>pa_tracts <span class="ot">&lt;-</span> <span class="fu">tracts</span>(<span class="at">state =</span> <span class="st">"PA"</span>, <span class="at">cb =</span> <span class="cn">TRUE</span>, <span class="at">year =</span> <span class="dv">2022</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="check-that-all-data-loaded-correctly" class="level1">
<h1>Check that all data loaded correctly</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that all data loaded correctly</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Check basic structure and CRS</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"PA Counties:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PA Counties:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Number of counties:"</span>, <span class="fu">nrow</span>(pa_counties)))  <span class="co"># Counts PA counties </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of counties: 67"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"CRS:"</span>, <span class="fu">st_crs</span>(pa_counties)<span class="sc">$</span>input))        <span class="co"># Shows coordinate system for counties</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRS: NAD83"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Hospitals:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hospitals:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Number of hospitals:"</span>, <span class="fu">nrow</span>(hospitals)))   <span class="co"># Counts hospitals in the dataset</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of hospitals: 223"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"CRS:"</span>, <span class="fu">st_crs</span>(hospitals)<span class="sc">$</span>input))          <span class="co"># Shows coordinate system for hospitals</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRS: WGS 84"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"PA Census Tracts:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "PA Census Tracts:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Number of census tracts:"</span>, <span class="fu">nrow</span>(pa_tracts)))  <span class="co"># Counts census tracts (should be ~3,000+)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of census tracts: 3445"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"CRS:"</span>, <span class="fu">st_crs</span>(pa_tracts)<span class="sc">$</span>input))             <span class="co"># Shows coordinate system for tracts</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRS: NAD83"</code></pre>
</div>
</div>
<hr>
<section id="step-2-get-demographic-data" class="level4">
<h4 class="anchored" data-anchor-id="step-2-get-demographic-data">Step 2: Get Demographic Data</h4>
<p>Use <code>tidycensus</code> to download tract-level demographic data for Pennsylvania.</p>
<p><strong>Required variables:</strong> - Total population - Median household income - Population 65 years and over (you may need to sum multiple age categories)</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get demographic data from ACS</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get tract-level demographic data for Pennsylvania</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the elderly population data</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We need to sum multiple age categories to get total 65+ population</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>pa_demographics_corrected <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">"tract"</span>,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">c</span>(</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> <span class="st">"B01003_001"</span>,           <span class="co"># Total population</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_income =</span> <span class="st">"B19013_001"</span>,       <span class="co"># Median household income</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age 65-69</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_65_69_male =</span> <span class="st">"B01001_020"</span>,      <span class="co"># Male 65-69</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_65_69_female =</span> <span class="st">"B01001_044"</span>,    <span class="co"># Female 65-69</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age 70-74</span></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_70_74_male =</span> <span class="st">"B01001_021"</span>,      <span class="co"># Male 70-74</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_70_74_female =</span> <span class="st">"B01001_045"</span>,    <span class="co"># Female 70-74</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age 75-79</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_75_79_male =</span> <span class="st">"B01001_022"</span>,      <span class="co"># Male 75-79</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_75_79_female =</span> <span class="st">"B01001_046"</span>,    <span class="co"># Female 75-79</span></span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age 80-84</span></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_80_84_male =</span> <span class="st">"B01001_023"</span>,      <span class="co"># Male 80-84</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_80_84_female =</span> <span class="st">"B01001_047"</span>,    <span class="co"># Female 80-84</span></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Age 85+</span></span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_85_plus_male =</span> <span class="st">"B01001_024"</span>,    <span class="co"># Male 85+</span></span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_85_plus_female =</span> <span class="st">"B01001_048"</span>   <span class="co"># Female 85+</span></span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"PA"</span>,</span>
<span id="cb24-28"><a href="#cb24-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2022</span>,</span>
<span id="cb24-29"><a href="#cb24-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="st">"wide"</span></span>
<span id="cb24-30"><a href="#cb24-30" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-31"><a href="#cb24-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-32"><a href="#cb24-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total population 65+</span></span>
<span id="cb24-33"><a href="#cb24-33" aria-hidden="true" tabindex="-1"></a>pa_demographics_corrected <span class="ot">&lt;-</span> pa_demographics_corrected <span class="sc">%&gt;%</span></span>
<span id="cb24-34"><a href="#cb24-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-35"><a href="#cb24-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop_65_plus_total =</span> age_65_69_maleE <span class="sc">+</span> age_65_69_femaleE <span class="sc">+</span> </span>
<span id="cb24-36"><a href="#cb24-36" aria-hidden="true" tabindex="-1"></a>                        age_70_74_maleE <span class="sc">+</span> age_70_74_femaleE <span class="sc">+</span></span>
<span id="cb24-37"><a href="#cb24-37" aria-hidden="true" tabindex="-1"></a>                        age_75_79_maleE <span class="sc">+</span> age_75_79_femaleE <span class="sc">+</span></span>
<span id="cb24-38"><a href="#cb24-38" aria-hidden="true" tabindex="-1"></a>                        age_80_84_maleE <span class="sc">+</span> age_80_84_femaleE <span class="sc">+</span></span>
<span id="cb24-39"><a href="#cb24-39" aria-hidden="true" tabindex="-1"></a>                        age_85_plus_maleE <span class="sc">+</span> age_85_plus_femaleE</span>
<span id="cb24-40"><a href="#cb24-40" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb24-41"><a href="#cb24-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-42"><a href="#cb24-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Join to tract boundaries</span></span>
<span id="cb24-43"><a href="#cb24-43" aria-hidden="true" tabindex="-1"></a>pa_tracts_with_data <span class="ot">&lt;-</span> pa_tracts <span class="sc">%&gt;%</span></span>
<span id="cb24-44"><a href="#cb24-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(pa_demographics_corrected, <span class="at">by =</span> <span class="st">"GEOID"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 1: What year of ACS data are you using?</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Question 1: What year of ACS data are you using?"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Question 1: What year of ACS data are you using?"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Answer: 2022 (we specified year = 2022 in get_acs())"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Answer: 2022 (we specified year = 2022 in get_acs())"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 2: How many tracts have missing income data?</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Question 2: How many tracts have missing income data?"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Question 2: How many tracts have missing income data?"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>missing_income <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(pa_tracts_with_data<span class="sc">$</span>median_incomeE))</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Answer:"</span>, missing_income, <span class="st">"tracts have missing income data"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Answer: 62 tracts have missing income data"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Question 3: What is the median income across all PA census tracts?</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Question 3: What is the median income across all PA census tracts?"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Question 3: What is the median income across all PA census tracts?"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>overall_median_income <span class="ot">&lt;-</span> <span class="fu">median</span>(pa_tracts_with_data<span class="sc">$</span>median_incomeE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Answer: $"</span>, <span class="fu">round</span>(overall_median_income, <span class="dv">0</span>), <span class="st">"is the median income across all PA tracts"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Answer: $ 70188 is the median income across all PA tracts"</code></pre>
</div>
</div>
<hr>
</section>
<section id="step-3-define-vulnerable-populations" class="level4">
<h4 class="anchored" data-anchor-id="step-3-define-vulnerable-populations">Step 3: Define Vulnerable Populations</h4>
<p>Identify census tracts with vulnerable populations based on TWO criteria: 1. Low median household income (choose an appropriate threshold) 2. Significant elderly population (choose an appropriate threshold)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define vulnerable populations using quartile approach</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>vulnerable_tracts <span class="ot">&lt;-</span> pa_tracts_with_data <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_elderly =</span> (pop_65_plus_total <span class="sc">/</span> total_popE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">low_income =</span> median_incomeE <span class="sc">&lt;</span> <span class="dv">55924</span>,           <span class="co"># Bottom quartile</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_elderly =</span> pct_elderly <span class="sc">&gt;=</span> <span class="fl">20.1</span>,            <span class="co"># Top quartile</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">vulnerable =</span> low_income <span class="sc">&amp;</span> high_elderly</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(median_incomeE))</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Vulnerable tracts:"</span>, <span class="fu">sum</span>(vulnerable_tracts<span class="sc">$</span>vulnerable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Vulnerable tracts: 148"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Percentage:"</span>, <span class="fu">round</span>(<span class="fu">sum</span>(vulnerable_tracts<span class="sc">$</span>vulnerable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">nrow</span>(vulnerable_tracts) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>), <span class="st">"%"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percentage: 4.37 %"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the quartiles of each category</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vulnerable_tracts<span class="sc">$</span>median_incomeE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  11558   55924   70188   77527   93287  250001 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vulnerable_tracts<span class="sc">$</span>pct_elderly)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00   12.49   16.53   16.54   20.11   63.07 </code></pre>
</div>
</div>
<p><strong>Questions to answer:</strong></p>
<p>Income Threshold: I chose a median household income threshold of $55,924, representing the first quartile (bottom 25%) of income distribution across Pennsylvania census tracts. Elderly Population Threshold: I selected 20.1% as the threshold for significant elderly population, representing the third quartile (top 25%) of elderly population distribution. These quartile-based thresholds were chosen to identify the most vulnerable populations given limited city resources for healthcare investment. By focusing on tracts in both the bottom quartile for income and the top quartile for elderly population, we ensure that our analysis prioritizes areas with the greatest need—where financial barriers to healthcare access coincide with high concentrations of elderly residents who face increased healthcare needs. Results: Using these criteria, 148 census tracts representing 4.37% of Pennsylvania census tracts meet both vulnerability criteria. This focused approach allows policymakers to target resources toward communities where vulnerable populations are most concentrated.</p>
<hr>
</section>
<section id="step-4-calculate-distance-to-hospitals" class="level4">
<h4 class="anchored" data-anchor-id="step-4-calculate-distance-to-hospitals">Step 4: Calculate Distance to Hospitals</h4>
<p>For each vulnerable tract, calculate the distance to the nearest hospital.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform to Pennsylvania South State Plane (EPSG:3365)</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>pa_counties_projected <span class="ot">&lt;-</span> pa_counties <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3365</span>)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>hospitals_projected <span class="ot">&lt;-</span> hospitals <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3365</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to vulnerable tracts and transform</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>vulnerable_tracts_projected <span class="ot">&lt;-</span> vulnerable_tracts <span class="sc">%&gt;%</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(vulnerable <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3365</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate distance from each vulnerable tract centroid to nearest hospital</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>vulnerable_tract_centroids <span class="ot">&lt;-</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_centroid</span>()</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>vulnerable_distances <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(vulnerable_tract_centroids, hospitals_projected)</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>vulnerable_tracts_projected <span class="ot">&lt;-</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist_to_hospital_ft =</span> <span class="fu">as.numeric</span>(<span class="fu">apply</span>(vulnerable_distances, <span class="dv">1</span>, min)),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist_to_hospital_mi =</span> dist_to_hospital_ft <span class="sc">/</span> <span class="dv">5280</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>avg_distance <span class="ot">&lt;-</span> <span class="fu">mean</span>(vulnerable_tracts_projected<span class="sc">$</span>dist_to_hospital_mi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Average distance to nearest hospital:"</span>, <span class="fu">round</span>(avg_distance, <span class="dv">2</span>), <span class="st">"miles"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Average distance to nearest hospital: 4.97 miles"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>max_distance <span class="ot">&lt;-</span> <span class="fu">max</span>(vulnerable_tracts_projected<span class="sc">$</span>dist_to_hospital_mi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Maximum distance:"</span>, <span class="fu">round</span>(max_distance, <span class="dv">2</span>), <span class="st">"miles"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Maximum distance: 19.16 miles"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>far_tracts <span class="ot">&lt;-</span> <span class="fu">sum</span>(vulnerable_tracts_projected<span class="sc">$</span>dist_to_hospital_mi <span class="sc">&gt;</span> <span class="dv">15</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Vulnerable tracts more than 15 miles from hospital:"</span>, far_tracts))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Vulnerable tracts more than 15 miles from hospital: 10"</code></pre>
</div>
</div>
<p><strong>Run these two chunks and let me know what you get!</strong></p>
<p><strong>Summary:</strong> Projection Choice: I used Pennsylvania South State Plane (EPSG:3365) because it’s optimized for accurate distance measurements within Pennsylvania. Unlike geographic coordinates (latitude/longitude) which measure in degrees, this projected coordinate system uses feet, allowing us to calculate actual distances in miles.</p>
<ul>
<li>Average distance to nearest hospital: 4.97 miles<br>
</li>
<li>Maximum distance: 19.16 miles</li>
<li><h1 id="of-vulnerable-tracts-15-miles-away-from-hospital-10">of vulnerable tracts 15&lt; miles away from hospital: 10</h1></li>
</ul>
<hr>
</section>
<section id="step-5-identify-underserved-areas" class="level4">
<h4 class="anchored" data-anchor-id="step-5-identify-underserved-areas">Step 5: Identify Underserved Areas</h4>
<p>Define “underserved” as vulnerable tracts that are more than 15 miles from the nearest hospital.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create underserved variable</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>vulnerable_tracts_projected <span class="ot">&lt;-</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">underserved =</span> dist_to_hospital_mi <span class="sc">&gt;</span> <span class="dv">15</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>underserved_count <span class="ot">&lt;-</span> <span class="fu">sum</span>(vulnerable_tracts_projected<span class="sc">$</span>underserved, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Underserved tracts:"</span>, underserved_count))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Underserved tracts: 10"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>pct_underserved <span class="ot">&lt;-</span> (underserved_count <span class="sc">/</span> <span class="fu">nrow</span>(vulnerable_tracts_projected)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Percentage of vulnerable tracts that are underserved:"</span>, <span class="fu">round</span>(pct_underserved, <span class="dv">2</span>), <span class="st">"%"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Percentage of vulnerable tracts that are underserved: 6.76 %"</code></pre>
</div>
</div>
<p>10 tracts are undeserved representing ~7% of the population. This number is slightly lower than I expected, as I would expected a higher proportion of undeserved populations to have limited access to hospitals; however, this still represents thousands of undeserved and extremely vulnerable individuals. It is possible that that these individuals are located in rural areas. Since a majority of the vulnerable population does live within 15 miles of hospitals, it is possible that they are located in more urban envirornments. In the next steps we will examine the spaital aspects of these findings.</p>
<hr>
</section>
<section id="step-6-aggregate-to-county-level" class="level4">
<h4 class="anchored" data-anchor-id="step-6-aggregate-to-county-level">Step 6: Aggregate to County Level</h4>
<p>Use spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spatial join to match vulnerable tracts to their counties</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>vulnerable_tracts_with_county <span class="ot">&lt;-</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_join</span>(pa_counties_projected, <span class="at">join =</span> st_within)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="aggregate-statistics-by-county" class="level1">
<h1>Aggregate statistics by county</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Aggregate statistics by county</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>county_summary <span class="ot">&lt;-</span> vulnerable_tracts_with_county <span class="sc">%&gt;%</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(NAMELSAD.y) <span class="sc">%&gt;%</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_vulnerable_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_underserved_tracts =</span> <span class="fu">sum</span>(underserved, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_underserved =</span> (num_underserved_tracts <span class="sc">/</span> num_vulnerable_tracts) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_distance_to_hospital =</span> <span class="fu">mean</span>(dist_to_hospital_mi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_vulnerable_pop =</span> <span class="fu">sum</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_underserved))</span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(county_summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 47 × 6
   NAMELSAD.y       num_vulnerable_tracts num_underserved_tracts pct_underserved
   &lt;chr&gt;                            &lt;int&gt;                  &lt;int&gt;           &lt;dbl&gt;
 1 Bradford County                      1                      1           100  
 2 Dauphin County                       1                      1           100  
 3 Forest County                        1                      1           100  
 4 Juniata County                       1                      1           100  
 5 Monroe County                        1                      1           100  
 6 Sullivan County                      1                      1           100  
 7 Wayne County                         2                      1            50  
 8 Potter County                        3                      1            33.3
 9 Crawford County                      4                      1            25  
10 Clearfield Coun…                     5                      1            20  
# ℹ 37 more rows
# ℹ 2 more variables: avg_distance_to_hospital &lt;dbl&gt;,
#   total_vulnerable_pop &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Required county-level statistics:</strong> - Number of vulnerable tracts - Number of underserved tracts<br>
- Percentage of vulnerable tracts that are underserved - Average distance to nearest hospital for vulnerable tracts - Total vulnerable population</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 5 counties by percentage of underserved vulnerable tracts</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>top_5_pct <span class="ot">&lt;-</span> county_summary <span class="sc">%&gt;%</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_underserved)) <span class="sc">%&gt;%</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAMELSAD.y, num_vulnerable_tracts, num_underserved_tracts, pct_underserved)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Top 5 counties by percentage of underserved vulnerable tracts:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Top 5 counties by percentage of underserved vulnerable tracts:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_5_pct)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  NAMELSAD.y      num_vulnerable_tracts num_underserved_tracts pct_underserved
  &lt;chr&gt;                           &lt;int&gt;                  &lt;int&gt;           &lt;dbl&gt;
1 Bradford County                     1                      1             100
2 Dauphin County                      1                      1             100
3 Forest County                       1                      1             100
4 Juniata County                      1                      1             100
5 Monroe County                       1                      1             100</code></pre>
</div>
</div>
<p>The above table looks at the top 5 counties that have the highest percentage of underserved vulnerable tracts. However, this data isn’t overwhelmingly telling of anything. It shows that the of the 1 vulnerable tract that each of these counties have, that tract is also underserved.These counties are likely somewhat rural, with the vulnerable population all clustered together in tract.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counties with most vulnerable people living far from hospitals</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>underserved_pop_by_county <span class="ot">&lt;-</span> vulnerable_tracts_with_county <span class="sc">%&gt;%</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(underserved <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(NAMELSAD.y) <span class="sc">%&gt;%</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">underserved_vulnerable_pop =</span> <span class="fu">sum</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_underserved_tracts =</span> <span class="fu">n</span>()</span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(underserved_vulnerable_pop)) <span class="sc">%&gt;%</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">5</span>)</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Top 5 counties with most vulnerable people living far from hospitals:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Top 5 counties with most vulnerable people living far from hospitals:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(underserved_pop_by_county)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  NAMELSAD.y        underserved_vulnerable_pop num_underserved_tracts
  &lt;chr&gt;                                  &lt;dbl&gt;                  &lt;int&gt;
1 Bradford County                         5466                      1
2 Dauphin County                          4018                      1
3 Clearfield County                       3343                      1
4 Forest County                           2701                      1
5 Crawford County                         2536                      1</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All counties with underserved vulnerable tracts</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>all_counties_underserved <span class="ot">&lt;-</span> vulnerable_tracts_with_county <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(underserved <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(NAMELSAD.y) <span class="sc">%&gt;%</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_underserved_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">underserved_vulnerable_pop =</span> <span class="fu">sum</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    county_summary <span class="sc">%&gt;%</span> <span class="fu">select</span>(NAMELSAD.y, num_vulnerable_tracts),</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"NAMELSAD.y"</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAMELSAD.y, num_vulnerable_tracts, num_underserved_tracts, underserved_vulnerable_pop) <span class="sc">%&gt;%</span></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(underserved_vulnerable_pop))</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"All counties with underserved vulnerable tracts:"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "All counties with underserved vulnerable tracts:"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(all_counties_underserved)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 4
   NAMELSAD.y        num_vulnerable_tracts num_underserved_tracts
   &lt;chr&gt;                             &lt;int&gt;                  &lt;int&gt;
 1 Bradford County                       1                      1
 2 Dauphin County                        1                      1
 3 Clearfield County                     5                      1
 4 Forest County                         1                      1
 5 Crawford County                       4                      1
 6 Potter County                         3                      1
 7 Wayne County                          2                      1
 8 Juniata County                        1                      1
 9 Monroe County                         1                      1
10 Sullivan County                       1                      1
# ℹ 1 more variable: underserved_vulnerable_pop &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Questions to answer:</strong> Several of the counties that have 1 underserved tract also have just 1 vulnerable. Many of these counties are rural, suggesting that a vulnerble tract (high elderly population and low income) is automatically considered underserved given the likely large distance between tracts in that rural county and hospitals. However, this is not always the case. For example, Dauphin County is right outside of Harrisburg and fairly urban, implying that the underserved tract there is likely on the very outskirts.</p>
<p>Places like Clearfield and Crawford have several vulnerable tracts, but only one underserved tract. This makes sense given their mixed nature with small cities. While more of their tracts are considered vulnerable, a lower proportion are underserved given their urban nature and distance to hospitals. This phenonmenon of high levels of vulnerability and low levels of underserved populations in urban areas is most evidently observed in Philadelphia, which has 17 vulnerable tracts yet 0 underserved tracts.</p>
<hr>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Top 10 counties by total vulnerable population</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Add population of underserved tracts</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>top_10_vulnerable <span class="ot">&lt;-</span> county_summary <span class="sc">%&gt;%</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    vulnerable_tracts_with_county <span class="sc">%&gt;%</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(underserved <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(NAMELSAD.y) <span class="sc">%&gt;%</span></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarize</span>(<span class="at">underserved_pop =</span> <span class="fu">sum</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"NAMELSAD.y"</span></span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_vulnerable_pop)) <span class="sc">%&gt;%</span></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>)</span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(top_10_vulnerable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
   NAMELSAD.y       num_vulnerable_tracts num_underserved_tracts pct_underserved
   &lt;chr&gt;                            &lt;int&gt;                  &lt;int&gt;           &lt;dbl&gt;
 1 Philadelphia Co…                    17                      0               0
 2 Allegheny County                    16                      0               0
 3 Fayette County                       7                      0               0
 4 Westmoreland Co…                    10                      0               0
 5 Clearfield Coun…                     5                      1              20
 6 Luzerne County                       7                      0               0
 7 Mercer County                        5                      0               0
 8 Cambria County                       6                      0               0
 9 Somerset County                      4                      0               0
10 Erie County                          3                      0               0
# ℹ 3 more variables: avg_distance_to_hospital &lt;dbl&gt;,
#   total_vulnerable_pop &lt;dbl&gt;, underserved_pop &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="step-7-create-summary-table" class="level4">
<h4 class="anchored" data-anchor-id="step-7-create-summary-table">Step 7: Create Summary Table</h4>
<p>Create a professional table showing the top 10 priority counties for healthcare investment.</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and format priority counties table</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Create top 10 priority counties table by vulnerable population</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>priority_counties <span class="ot">&lt;-</span> county_summary <span class="sc">%&gt;%</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>    vulnerable_tracts_with_county <span class="sc">%&gt;%</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(underserved <span class="sc">==</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(NAMELSAD.y) <span class="sc">%&gt;%</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarize</span>(<span class="at">underserved_pop =</span> <span class="fu">sum</span>(total_popE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"NAMELSAD.y"</span></span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_vulnerable_pop)) <span class="sc">%&gt;%</span></span>
<span id="cb73-14"><a href="#cb73-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb73-15"><a href="#cb73-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(NAMELSAD.y, num_vulnerable_tracts, num_underserved_tracts, </span>
<span id="cb73-16"><a href="#cb73-16" aria-hidden="true" tabindex="-1"></a>         pct_underserved, avg_distance_to_hospital, total_vulnerable_pop, underserved_pop)</span>
<span id="cb73-17"><a href="#cb73-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-18"><a href="#cb73-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Format and display table</span></span>
<span id="cb73-19"><a href="#cb73-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb73-20"><a href="#cb73-20" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(priority_counties,</span>
<span id="cb73-21"><a href="#cb73-21" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Vulnerable Tracts"</span>, <span class="st">"Underserved Tracts"</span>, </span>
<span id="cb73-22"><a href="#cb73-22" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"% Underserved"</span>, <span class="st">"Avg Distance (mi)"</span>, <span class="st">"Vulnerable Population"</span>, <span class="st">"Underserved Population"</span>),</span>
<span id="cb73-23"><a href="#cb73-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">digits =</span> <span class="dv">2</span>,</span>
<span id="cb73-24"><a href="#cb73-24" aria-hidden="true" tabindex="-1"></a>      <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">","</span>),</span>
<span id="cb73-25"><a href="#cb73-25" aria-hidden="true" tabindex="-1"></a>      <span class="at">caption =</span> <span class="st">"Top 10 Priority Counties for Healthcare Investment (ranked by total vulnerable population)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 10 Priority Counties for Healthcare Investment (ranked by total vulnerable population)</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Vulnerable Tracts</th>
<th style="text-align: right;">Underserved Tracts</th>
<th style="text-align: right;">% Underserved</th>
<th style="text-align: right;">Avg Distance (mi)</th>
<th style="text-align: right;">Vulnerable Population</th>
<th style="text-align: right;">Underserved Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Philadelphia County</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.83</td>
<td style="text-align: right;">61,779</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Allegheny County</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.72</td>
<td style="text-align: right;">35,215</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fayette County</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.92</td>
<td style="text-align: right;">22,199</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Westmoreland County</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">21,513</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clearfield County</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">12.16</td>
<td style="text-align: right;">19,828</td>
<td style="text-align: right;">3,343</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luzerne County</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.04</td>
<td style="text-align: right;">18,702</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mercer County</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.78</td>
<td style="text-align: right;">16,686</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cambria County</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.97</td>
<td style="text-align: right;">13,301</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Somerset County</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">8.48</td>
<td style="text-align: right;">11,454</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Erie County</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">4.63</td>
<td style="text-align: right;">10,511</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Requirements:</strong> - Use <code>knitr::kable()</code> or similar for formatting - Include descriptive column names - Format numbers appropriately (commas for population, percentages, etc.) - Add an informative caption - Sort by priority (you decide the metric)</p>
<hr>
</section>
<section id="part-2-comprehensive-visualization" class="level2">
<h2 class="anchored" data-anchor-id="part-2-comprehensive-visualization">Part 2: Comprehensive Visualization</h2>
<p>Using the skills from Week 3 (Data Visualization), create publication-quality maps and charts.</p>
<section id="map-1-county-level-choropleth" class="level3">
<h3 class="anchored" data-anchor-id="map-1-county-level-choropleth">Map 1: County-Level Choropleth</h3>
<p>Create a choropleth map showing healthcare access challenges at the county level.</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create county-level access map</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Join county summary data to county spatial boundaries</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out counties with no vulnerable tracts (to remove gray areas)</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>counties_for_map <span class="ot">&lt;-</span> pa_counties_projected <span class="sc">%&gt;%</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(county_summary, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"NAMELSAD"</span> <span class="ot">=</span> <span class="st">"NAMELSAD.y"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_underserved =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(pct_underserved), <span class="dv">0</span>, pct_underserved))</span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the map</span></span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># County fill by percentage underserved</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> counties_for_map, </span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>          <span class="fu">aes</span>(<span class="at">fill =</span> pct_underserved), </span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"white"</span>, </span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Hospital locations as points</span></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> hospitals_projected, </span>
<span id="cb74-17"><a href="#cb74-17" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"darkblue"</span>, </span>
<span id="cb74-18"><a href="#cb74-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">1.2</span>, </span>
<span id="cb74-19"><a href="#cb74-19" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.7</span>,</span>
<span id="cb74-20"><a href="#cb74-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">shape =</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Shape 3 = plus sign (cross)</span></span>
<span id="cb74-21"><a href="#cb74-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Color scheme</span></span>
<span id="cb74-22"><a href="#cb74-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightyellow"</span>, </span>
<span id="cb74-23"><a href="#cb74-23" aria-hidden="true" tabindex="-1"></a>                      <span class="at">high =</span> <span class="st">"darkred"</span>,</span>
<span id="cb74-24"><a href="#cb74-24" aria-hidden="true" tabindex="-1"></a>                      <span class="at">name =</span> <span class="st">"% Underserved"</span>) <span class="sc">+</span></span>
<span id="cb74-25"><a href="#cb74-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Labels and theme</span></span>
<span id="cb74-26"><a href="#cb74-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Healthcare Access for Vulnerable Populations in Pennsylvania"</span>,</span>
<span id="cb74-27"><a href="#cb74-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Percentage of vulnerable tracts underserved by county (+ symbols = hospitals)"</span>,</span>
<span id="cb74-28"><a href="#cb74-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Source: 2022 ACS 5-Year Estimates, PA Hospital Data</span><span class="sc">\n</span><span class="st">Vulnerable = low income (bottom 25%) + high elderly (top 25%)</span><span class="sc">\n</span><span class="st">Underserved = &gt;15 miles from nearest hospital"</span>) <span class="sc">+</span></span>
<span id="cb74-29"><a href="#cb74-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb74-30"><a href="#cb74-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb74-31"><a href="#cb74-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb74-32"><a href="#cb74-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb74-33"><a href="#cb74-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb74-34"><a href="#cb74-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb74-35"><a href="#cb74-35" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sen_Sam_Assignment2_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above map shows the percent of vulnerable tracts that are underserved and the location of hospitals marked by the dark blue “+” symbols per the assignments instructions. As can be seen, these large counties have very few hospitals, with a 3 of them having no hospitals at all.</p>
<p>However, the map is somewhat misleading. Many of these counties only have 1 tract that is vulnerable. This map makes could be misleading in making it seem like these whole counties are vulnerable and underserved.</p>
<hr>
</section>
<section id="map-2-detailed-vulnerability-map" class="level3">
<h3 class="anchored" data-anchor-id="map-2-detailed-vulnerability-map">Map 2: Detailed Vulnerability Map</h3>
<p>Create a map highlighting underserved vulnerable tracts.</p>
<p><strong>Your Task:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Map 2 with bolder vulnerable tracts</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> pa_counties_projected, </span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">"gray95"</span>, </span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"gray60"</span>, </span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span> <span class="fu">filter</span>(vulnerable <span class="sc">==</span> <span class="cn">TRUE</span>, underserved <span class="sc">==</span> <span class="cn">FALSE</span>),</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"blue"</span>,  <span class="co"># Add outline</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.5</span>,</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> vulnerable_tracts_projected <span class="sc">%&gt;%</span> <span class="fu">filter</span>(underserved <span class="sc">==</span> <span class="cn">TRUE</span>),</span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="st">"darkred"</span>,</span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.7</span>,</span>
<span id="cb75-16"><a href="#cb75-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.9</span>) <span class="sc">+</span></span>
<span id="cb75-17"><a href="#cb75-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> hospitals_projected,</span>
<span id="cb75-18"><a href="#cb75-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb75-19"><a href="#cb75-19" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">1.5</span>,</span>
<span id="cb75-20"><a href="#cb75-20" aria-hidden="true" tabindex="-1"></a>          <span class="at">alpha =</span> <span class="fl">0.8</span>,</span>
<span id="cb75-21"><a href="#cb75-21" aria-hidden="true" tabindex="-1"></a>          <span class="at">shape =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb75-22"><a href="#cb75-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Underserved Vulnerable Populations in Pennsylvania"</span>,</span>
<span id="cb75-23"><a href="#cb75-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red = underserved vulnerable tracts (&gt;15 mi from hospital) | Blue = other vulnerable tracts | + = Hospitals"</span>,</span>
<span id="cb75-24"><a href="#cb75-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Source: 2022 ACS 5-Year Estimates, PA Hospital Data"</span>) <span class="sc">+</span></span>
<span id="cb75-25"><a href="#cb75-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb75-26"><a href="#cb75-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb75-27"><a href="#cb75-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb75-28"><a href="#cb75-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb75-29"><a href="#cb75-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">hjust =</span> <span class="dv">0</span>)</span>
<span id="cb75-30"><a href="#cb75-30" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sen_Sam_Assignment2_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above map shows vulnerable tracts in light blue with a dark boarder, and vulnerable underserved tracts in dark red. As can be seen, none of the dark red tracts have a hospital in them. For Philadelphia, despite having many hospitals, there are still the highest number of vulnerable tracts.</p>
<hr>
</section>
<section id="chart-distribution-analysis" class="level3">
<h3 class="anchored" data-anchor-id="chart-distribution-analysis">Chart: Distribution Analysis</h3>
<p>Create a visualization showing the distribution of distances to hospitals for vulnerable populations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create histogram showing distribution of distances to hospitals for vulnerable populations</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vulnerable_tracts_projected <span class="sc">%&gt;%</span> <span class="fu">filter</span>(vulnerable <span class="sc">==</span> <span class="cn">TRUE</span>), </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> dist_to_hospital_mi)) <span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">20</span>, </span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">"steelblue"</span>, </span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">"white"</span>, </span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">15</span>, </span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="st">"dashed"</span>, </span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, </span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="fl">15.5</span>, </span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">y =</span> <span class="cn">Inf</span>, </span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="st">"15 mile threshold"</span>, </span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">vjust =</span> <span class="fl">1.5</span>, </span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">hjust =</span> <span class="dv">0</span>, </span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Distance to Nearest Hospital for Vulnerable Tracts"</span>,</span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Distance to Nearest Hospital (miles)"</span>,</span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Tracts"</span>) <span class="sc">+</span></span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>)</span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sen_Sam_Assignment2_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram above shows that a majority of vulnerable populations live within 10 miles of hospitals. With only a few living more than 15 miles away from a hospital, qualifying them as underserved. These populations are at a very high level of risk, but many other factors in addition to distance from a hospital can put vulnerable populations at risk. Of the top 10 counties with the highest vulnerable populations, one of the counties - Clearfield - has a tract that that is also underserved.</p>
<p><strong>Suggested chart types:</strong> - Histogram or density plot of distances - Box plot comparing distances across regions - Bar chart of underserved tracts by county - Scatter plot of distance vs.&nbsp;vulnerable population size</p>
<p><strong>Requirements:</strong> - Clear axes labels with units - Appropriate title - Professional formatting - Brief interpretation (1-2 sentences as a caption or in text)</p>
<hr>
</section>
</section>
<section id="part-3-bring-your-own-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-3-bring-your-own-data-analysis">Part 3: Bring Your Own Data Analysis</h2>
<p>Choose your own additional spatial dataset and conduct a supplementary analysis.</p>
<section id="challenge-options" class="level3">
<h3 class="anchored" data-anchor-id="challenge-options">Challenge Options</h3>
<p>Choose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/).</p>
<p><strong>Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question</strong></p>
<hr>
<section id="education-youth-services" class="level4">
<h4 class="anchored" data-anchor-id="education-youth-services">Education &amp; Youth Services</h4>
<p><strong>Option A: Educational Desert Analysis</strong> - <strong>Data:</strong> Schools, Libraries, Recreation Centers, Census tracts (child population) - <strong>Question:</strong> “Which neighborhoods lack adequate educational infrastructure for children?” - <strong>Operations:</strong> Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density - <strong>Policy relevance:</strong> School district planning, library placement, after-school program siting</p>
<p><strong>Option B: School Safety Zones</strong> - <strong>Data:</strong> Schools, Crime Incidents, Bike Network - <strong>Question:</strong> “Are school zones safe for walking/biking, or are they crime hotspots?” - <strong>Operations:</strong> Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage - <strong>Policy relevance:</strong> Safe Routes to School programs, crossing guard placement</p>
<hr>
</section>
<section id="environmental-justice" class="level4">
<h4 class="anchored" data-anchor-id="environmental-justice">Environmental Justice</h4>
<p><strong>Option C: Green Space Equity</strong> - <strong>Data:</strong> Parks, Street Trees, Census tracts (race/income demographics) - <strong>Question:</strong> “Do low-income and minority neighborhoods have equitable access to green space?” - <strong>Operations:</strong> Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics - <strong>Policy relevance:</strong> Climate resilience, environmental justice, urban forestry investment —</p>
</section>
<section id="public-safety-justice" class="level4">
<h4 class="anchored" data-anchor-id="public-safety-justice">Public Safety &amp; Justice</h4>
<p><strong>Option D: Crime &amp; Community Resources</strong> - <strong>Data:</strong> Crime Incidents, Recreation Centers, Libraries, Street Lights - <strong>Question:</strong> “Are high-crime areas underserved by community resources?” - <strong>Operations:</strong> Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis - <strong>Policy relevance:</strong> Community investment, violence prevention strategies —</p>
</section>
<section id="infrastructure-services" class="level4">
<h4 class="anchored" data-anchor-id="infrastructure-services">Infrastructure &amp; Services</h4>
<p><strong>Option E: Polling Place Accessibility</strong> - <strong>Data:</strong> Polling Places, SEPTA stops, Census tracts (elderly population, disability rates) - <strong>Question:</strong> “Are polling places accessible for elderly and disabled voters?” - <strong>Operations:</strong> Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access - <strong>Policy relevance:</strong> Voting rights, election infrastructure, ADA compliance</p>
<hr>
</section>
<section id="health-wellness" class="level4">
<h4 class="anchored" data-anchor-id="health-wellness">Health &amp; Wellness</h4>
<p><strong>Option F: Recreation &amp; Population Health</strong> - <strong>Data:</strong> Recreation Centers, Playgrounds, Parks, Census tracts (demographics) - <strong>Question:</strong> “Is lack of recreation access associated with vulnerable populations?” - <strong>Operations:</strong> Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators - <strong>Policy relevance:</strong> Public health investment, recreation programming, obesity prevention</p>
<hr>
</section>
<section id="emergency-services" class="level4">
<h4 class="anchored" data-anchor-id="emergency-services">Emergency Services</h4>
<p><strong>Option G: EMS Response Coverage</strong> - <strong>Data:</strong> Fire Stations, EMS stations, Population density, High-rise buildings - <strong>Question:</strong> “Are population-dense areas adequately covered by emergency services?” - <strong>Operations:</strong> Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas - <strong>Policy relevance:</strong> Emergency preparedness, station siting decisions</p>
<hr>
</section>
<section id="arts-culture" class="level4">
<h4 class="anchored" data-anchor-id="arts-culture">Arts &amp; Culture</h4>
<p><strong>Option H: Cultural Asset Distribution</strong> - <strong>Data:</strong> Public Art, Museums, Historic sites/markers, Neighborhoods - <strong>Question:</strong> “Do all neighborhoods have equitable access to cultural amenities?” - <strong>Operations:</strong> Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups - <strong>Policy relevance:</strong> Cultural equity, tourism, quality of life, neighborhood identity</p>
<hr>
</section>
</section>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources">Data Sources</h3>
<p><strong>OpenDataPhilly:</strong> https://opendataphilly.org/datasets/ - Most datasets available as GeoJSON, Shapefile, or CSV with coordinates - Always check the Metadata for a data dictionary of the fields.</p>
<p><strong>Additional Sources:</strong> - <strong>Pennsylvania Open Data:</strong> https://data.pa.gov/ - <strong>Census Bureau (via tidycensus):</strong> Demographics, economic indicators, commute patterns - <strong>TIGER/Line (via tigris):</strong> Geographic boundaries</p>
</section>
<section id="recommended-starting-points" class="level3">
<h3 class="anchored" data-anchor-id="recommended-starting-points">Recommended Starting Points</h3>
<p><strong>If you’re feeling confident:</strong> Choose an advanced challenge with multiple data layers. <strong>If you are a beginner, choose something more manageable that helps you understand the basics</strong></p>
<p><strong>If you have a different idea:</strong> Propose your own question! Just make sure: - You can access the spatial data - You can perform at least 2 spatial operations</p>
</section>
<section id="your-analysis" class="level3">
<h3 class="anchored" data-anchor-id="your-analysis">Your Analysis</h3>
<p><strong>Your Task:</strong></p>
<ol type="1">
<li><strong>Find and load additional data</strong>
<ul>
<li>Document your data source</li>
<li>Check and standardize the CRS</li>
<li>Provide basic summary statistics</li>
</ul></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load recreation centers dataset</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>rec_centers <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/PPR_Program_Sites.geojson"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `PPR_Program_Sites' from data source 
  `C:\Users\16468\OneDrive - PennO365\Documents\Academics\MUSA\Public_Policy_Analytics\portfolio-setup-ssen-droid\Assignments\Assignment_2\data\PPR_Program_Sites.geojson' 
  using driver `GeoJSON'
Simple feature collection with 171 features and 10 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -75.2563 ymin: 39.90444 xmax: -74.96944 ymax: 40.12284
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check basic information</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Number of recreation centers:"</span>, <span class="fu">nrow</span>(rec_centers)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Number of recreation centers: 171"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"CRS:"</span>, <span class="fu">st_crs</span>(rec_centers)<span class="sc">$</span>input))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CRS: WGS 84"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check what columns we have</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(rec_centers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "OBJECTID"     "PARK_NAME"    "DPP_ASSET_ID" "PROGRAM_TYPE" "SITE_CLASS"  
 [6] "BUILDING"     "GYM"          "LABEL_NUMBER" "COMMENTS"     "DATA_SOURCE" 
[11] "geometry"    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View first few rows to understand the data</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rec_centers)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 10 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -75.2563 ymin: 39.96572 xmax: -75.16713 ymax: 39.97446
Geodetic CRS:  WGS 84
  OBJECTID                          PARK_NAME DPP_ASSET_ID PROGRAM_TYPE
1      807 Tiffany Fletcher Recreation Center         1911      PPR_REC
2      808        Roberto Clemente Playground         1831      PPR_REC
3      809              Miles Mack Playground         1910      PPR_REC
4      810      William T Granahan Playground         1864      PPR_REC
5      811     Francisville Recreation Center         1859      PPR_REC
6      812          Charles A Papa Playground         1929      PPR_REC
  SITE_CLASS BUILDING GYM LABEL_NUMBER
1          A        Y   N         &lt;NA&gt;
2          B        Y   N         &lt;NA&gt;
3          A        Y   N         &lt;NA&gt;
4          B        Y   N         &lt;NA&gt;
5          A        Y   N         &lt;NA&gt;
6          A        Y   N         &lt;NA&gt;
                                                            COMMENTS
1 Former name Mill Creek Playground and Recreation Center (12/2022).
2                                                                   
3                                                                   
4                                    Located within Cobbs Creek Park
5                                                                   
6                                            Located in Morris Park.
     DATA_SOURCE                   geometry
1 Programs 11/24 POINT (-75.21582 39.96598)
2 Programs 11/24 POINT (-75.16794 39.96572)
3 Programs 11/24 POINT (-75.19562 39.96748)
4 Programs 11/24  POINT (-75.2504 39.96936)
5 Programs 11/24  POINT (-75.16713 39.9685)
6 Programs 11/24  POINT (-75.2563 39.97446)</code></pre>
</div>
</div>
<p>I chose the Philadelphia Parks &amp; Recreation (PPR) Program Sites dataset. This dataset contains recreation centers, playgrounds, and other youth-focused facilities operated by Philadelphia Parks &amp; Recreation. I selected this dataset because recreation centers provide critical after-school programming, sports facilities, and community activities for children and youth, making them an important complement to the hospital access analysis from Part 1. This analysis will examine whether vulnerable populations (low-income elderly) live in areas that also lack youth educational and recreational resources.</p>
<p>Data source: OpenDataPhilly (Philadelphia Parks &amp; Recreation Department). The dataset was last updated in November 2024 according to the “Programs 11/24” notation in the data source field.</p>
<p>The dataset contains 171 recreation facilities across Philadelphia.</p>
<p>The data is in WGS 84 (EPSG:4326), a geographic coordinate system. We will need to transform it (see below) to Pennsylvania South State Plane (EPSG:3365) to match the projected coordinate system used in Part 1 and enable accurate distance calculations in miles.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform recreation centers to Pennsylvania South State Plane (EPSG:3365)</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>rec_centers_projected <span class="ot">&lt;-</span> rec_centers <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3365</span>)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check that transformation worked</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Recreation centers CRS:"</span>, <span class="fu">st_crs</span>(rec_centers_projected)<span class="sc">$</span>input))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Recreation centers CRS: EPSG:3365"</code></pre>
</div>
</div>
<hr>
<ol start="2" type="1">
<li><strong>Research question</strong></li>
</ol>
<p>Do vulnerable populations in Philadelphia have adequate access to recreation centers compared to non-vulnerable populations?</p>
<hr>
<ol start="3" type="1">
<li><strong>Conduct spatial analysis</strong></li>
</ol>
<p>Use at least TWO spatial operations to answer your research question.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to Philadelphia County only using GEOID</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Philadelphia County FIPS code is 42101 (42 = PA, 101 = Philadelphia)</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>philly_tracts <span class="ot">&lt;-</span> pa_tracts_with_data <span class="sc">%&gt;%</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">str_starts</span>(GEOID, <span class="st">"42101"</span>)) <span class="sc">%&gt;%</span>  <span class="co"># Filter for Philadelphia County</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3365</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_elderly =</span> (pop_65_plus_total <span class="sc">/</span> total_popE) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">low_income =</span> median_incomeE <span class="sc">&lt;</span> <span class="dv">55924</span>,</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">high_elderly =</span> pct_elderly <span class="sc">&gt;=</span> <span class="fl">20.1</span>,</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">vulnerable =</span> low_income <span class="sc">&amp;</span> high_elderly</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(median_incomeE))</span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Check how many tracts we got</span></span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Philadelphia tracts:"</span>, <span class="fu">nrow</span>(philly_tracts)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Philadelphia tracts: 383"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Vulnerable tracts:"</span>, <span class="fu">sum</span>(philly_tracts<span class="sc">$</span>vulnerable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Vulnerable tracts: 17"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Non-vulnerable tracts:"</span>, <span class="fu">sum</span>(<span class="sc">!</span>philly_tracts<span class="sc">$</span>vulnerable, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Non-vulnerable tracts: 366"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate distance for all Philadelphia tracts</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>philly_centroids <span class="ot">&lt;-</span> <span class="fu">st_centroid</span>(philly_tracts)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>distances_to_rec <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(philly_centroids, rec_centers_projected)</span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>philly_tracts <span class="ot">&lt;-</span> philly_tracts <span class="sc">%&gt;%</span></span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist_to_rec_ft =</span> <span class="fu">as.numeric</span>(<span class="fu">apply</span>(distances_to_rec, <span class="dv">1</span>, min)),</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">dist_to_rec_mi =</span> dist_to_rec_ft <span class="sc">/</span> <span class="dv">5280</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics by vulnerability status</span></span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>access_comparison <span class="ot">&lt;-</span> philly_tracts <span class="sc">%&gt;%</span></span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_drop_geometry</span>() <span class="sc">%&gt;%</span></span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(vulnerable) <span class="sc">%&gt;%</span></span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_tracts =</span> <span class="fu">n</span>(),</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_dist_to_rec =</span> <span class="fu">mean</span>(dist_to_rec_mi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">median_dist_to_rec =</span> <span class="fu">median</span>(dist_to_rec_mi, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_within_half_mile =</span> <span class="fu">sum</span>(dist_to_rec_mi <span class="sc">&lt;=</span> <span class="fl">0.5</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">/</span> <span class="fu">n</span>() <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(access_comparison)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  vulnerable num_tracts avg_dist_to_rec median_dist_to_rec pct_within_half_mile
  &lt;lgl&gt;           &lt;int&gt;           &lt;dbl&gt;              &lt;dbl&gt;                &lt;dbl&gt;
1 FALSE             366           0.371              0.335                 80.1
2 TRUE               17           0.433              0.366                 70.6</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Map showing distance colored, with vulnerable tracts outlined</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># All tracts colored by distance</span></span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> philly_tracts,</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">aes</span>(<span class="at">fill =</span> dist_to_rec_mi),</span>
<span id="cb98-6"><a href="#cb98-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb98-7"><a href="#cb98-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb98-8"><a href="#cb98-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add thick border around vulnerable tracts</span></span>
<span id="cb98-9"><a href="#cb98-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> philly_tracts <span class="sc">%&gt;%</span> <span class="fu">filter</span>(vulnerable <span class="sc">==</span> <span class="cn">TRUE</span>),</span>
<span id="cb98-10"><a href="#cb98-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="cn">NA</span>,  <span class="co"># No fill, just outline</span></span>
<span id="cb98-11"><a href="#cb98-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb98-12"><a href="#cb98-12" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span>  <span class="co"># Thick red outline</span></span>
<span id="cb98-13"><a href="#cb98-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Recreation centers - smaller triangles</span></span>
<span id="cb98-14"><a href="#cb98-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> rec_centers_projected,</span>
<span id="cb98-15"><a href="#cb98-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">"darkgreen"</span>,</span>
<span id="cb98-16"><a href="#cb98-16" aria-hidden="true" tabindex="-1"></a>          <span class="at">size =</span> <span class="dv">1</span>,  <span class="co"># Smaller size</span></span>
<span id="cb98-17"><a href="#cb98-17" aria-hidden="true" tabindex="-1"></a>          <span class="at">shape =</span> <span class="dv">17</span>) <span class="sc">+</span></span>
<span id="cb98-18"><a href="#cb98-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"lightblue"</span>, <span class="at">high =</span> <span class="st">"orange"</span>,</span>
<span id="cb98-19"><a href="#cb98-19" aria-hidden="true" tabindex="-1"></a>                      <span class="at">name =</span> <span class="st">"Distance (mi)</span><span class="sc">\n</span><span class="st">to Rec Center"</span>) <span class="sc">+</span></span>
<span id="cb98-20"><a href="#cb98-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Recreation Center Access in Philadelphia: Vulnerable vs Non-Vulnerable Tracts"</span>,</span>
<span id="cb98-21"><a href="#cb98-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red outline = Vulnerable tracts | Green triangles = Recreation Centers"</span>,</span>
<span id="cb98-22"><a href="#cb98-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Source: Philadelphia Parks &amp; Recreation, 2022 ACS</span><span class="sc">\n</span><span class="st">Vulnerable = low income + high elderly population"</span>) <span class="sc">+</span></span>
<span id="cb98-23"><a href="#cb98-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb98-24"><a href="#cb98-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb98-25"><a href="#cb98-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb98-26"><a href="#cb98-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb98-27"><a href="#cb98-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb98-28"><a href="#cb98-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"right"</span></span>
<span id="cb98-29"><a href="#cb98-29" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Sen_Sam_Assignment2_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>The analysis reveals modest disparities in recreation center access between vulnerable and non-vulnerable populations in Philadelphia. Vulnerable tracts are located an average of 0.43 miles from the nearest recreation center compared to 0.37 miles for non-vulnerable tracts, and only 70.6% of vulnerable tracts fall within a half-mile walking distance compared to 80.1% of non-vulnerable tracts. While these differences suggest that vulnerable populations may have slightly worse access to recreational facilities, further statistical testing would be necessary to determine whether these observed differences are statistically significant or could be attributed to random chance. A permutation test or similar randomization procedure would help establish whether the 0.06-mile average difference and the 9.5 percentage point gap in coverage represent meaningful disparities requiring policy intervention. Overall, both groups demonstrate relatively good access to recreation centers, with most Philadelphia tracts located within comfortable walking distance of these facilities.</p>
</section>
</section>
<section id="finally---a-few-comments-about-your-incorporation-of-feedback" class="level2">
<h2 class="anchored" data-anchor-id="finally---a-few-comments-about-your-incorporation-of-feedback">Finally - A few comments about your incorporation of feedback!</h2>
<p>This time around I tried to format a little better and delete extraneous lines, such as “Your Task” and various instructions. I kept some of the instructions for ease of review as necessary.</p>
<hr>
</section>
<section id="submission-requirements" class="level2">
<h2 class="anchored" data-anchor-id="submission-requirements">Submission Requirements</h2>
<p><strong>What to submit:</strong></p>
<ol type="1">
<li><strong>Rendered HTML document posted to your course portfolio</strong> with all code, outputs, maps, and text
<ul>
<li>Use <code>embed-resources: true</code> in YAML so it’s a single file</li>
<li>All code should run without errors</li>
<li>All maps and charts should display correctly</li>
</ul></li>
</ol>
<p><strong>File naming:</strong> <code>LastName_FirstName_Assignment2.html</code> and <code>LastName_FirstName_Assignment2.qmd</code></p>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>