<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>assignment5_sen_sam – Sam Sen - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sam Sen - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../Labs/Lab 0/Scripts/lab0_template.html">
 <span class="dropdown-text">Lab 0</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Assignments</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_1/assignment_1.html">
 <span class="dropdown-text">Assignment 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_2/Sen_Sam_Assignment2.html">
 <span class="dropdown-text">Assignment 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_4/Assignment4_Sen_Sam.html">
 <span class="dropdown-text">Assignment 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Assignments/Assignment_5/Assignment5_Sen_Sam.html">
 <span class="dropdown-text">Assignment 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-notes" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Weekly Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-weekly-notes">    
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-01-notes.html">
 <span class="dropdown-text">Week 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-02-notes.html">
 <span class="dropdown-text">Week 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-04-notes.html">
 <span class="dropdown-text">Week 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../weekly-notes/week-05-notes.html">
 <span class="dropdown-text">Week 5</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-5" id="toc-assignment-5" class="nav-link active" data-scroll-target="#assignment-5">Assignment 5</a>
  <ul class="collapse">
  <li><a href="#part-1-indigo-rideshare-data-q4-2024" id="toc-part-1-indigo-rideshare-data-q4-2024" class="nav-link" data-scroll-target="#part-1-indigo-rideshare-data-q4-2024">Part 1: Indigo Rideshare Data: Q4 2024</a>
  <ul class="collapse">
  <li><a href="#download-and-adapt-data" id="toc-download-and-adapt-data" class="nav-link" data-scroll-target="#download-and-adapt-data">Download and Adapt Data</a></li>
  <li><a href="#model-creation" id="toc-model-creation" class="nav-link" data-scroll-target="#model-creation">Model Creation</a></li>
  <li><a href="#mae-and-result-comparison" id="toc-mae-and-result-comparison" class="nav-link" data-scroll-target="#mae-and-result-comparison">MAE and Result Comparison</a></li>
  </ul></li>
  <li><a href="#part-ii-error-analysis" id="toc-part-ii-error-analysis" class="nav-link" data-scroll-target="#part-ii-error-analysis">Part II: Error Analysis</a>
  <ul class="collapse">
  <li><a href="#spatial-patterns" id="toc-spatial-patterns" class="nav-link" data-scroll-target="#spatial-patterns">Spatial Patterns</a></li>
  <li><a href="#temporal-patterns" id="toc-temporal-patterns" class="nav-link" data-scroll-target="#temporal-patterns">Temporal Patterns</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="assignment-5" class="level1">
<h1>Assignment 5</h1>
<p><strong>Sam Sen</strong> <strong>MUSA 5080</strong></p>
<section id="part-1-indigo-rideshare-data-q4-2024" class="level2">
<h2 class="anchored" data-anchor-id="part-1-indigo-rideshare-data-q4-2024">Part 1: Indigo Rideshare Data: Q4 2024</h2>
<section id="download-and-adapt-data" class="level3">
<h3 class="anchored" data-anchor-id="download-and-adapt-data">Download and Adapt Data</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(riem)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'riem' was built under R version 4.5.2</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tigris)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>To enable caching of data, set `options(tigris_use_cache = TRUE)`
in your R script or .Rprofile.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Linking to GEOS 3.13.1, GDAL 3.11.0, PROJ 9.6.0; sf_use_s2() is TRUE</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong><em>We begin by loading the main packages for the analysis. tidyverse and lubridate handle data wrangling and date–time manipulation. riem provides historical weather data from airport stations. I also loaded spatial packages (tigris, sf) and ggplot2 for visualization. I then installed and attached riem to query Philadelphia weather data</em></strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>indego <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Data/indego-trips-2024-q4.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 299121 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (6): start_time, end_time, bike_id, trip_route_category, passholder_type...
dbl (9): trip_id, duration, start_station, start_lat, start_lon, end_station...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(indego)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 299,121
Columns: 15
$ trip_id             &lt;dbl&gt; 1050296434, 1050293063, 1050296229, 1050276817, 10…
$ duration            &lt;dbl&gt; 22, 8, 12, 1, 5, 9, 5, 6, 16, 16, 16, 39, 6, 40, 1…
$ start_time          &lt;chr&gt; "10/1/2024 0:00", "10/1/2024 0:06", "10/1/2024 0:0…
$ end_time            &lt;chr&gt; "10/1/2024 0:22", "10/1/2024 0:14", "10/1/2024 0:1…
$ start_station       &lt;dbl&gt; 3322, 3166, 3007, 3166, 3075, 3166, 3030, 3010, 33…
$ start_lat           &lt;dbl&gt; 39.93638, 39.97195, 39.94517, 39.97195, 39.96718, …
$ start_lon           &lt;dbl&gt; -75.15526, -75.13445, -75.15993, -75.13445, -75.16…
$ end_station         &lt;dbl&gt; 3375, 3017, 3244, 3166, 3102, 3008, 3203, 3163, 33…
$ end_lat             &lt;dbl&gt; 39.96036, 39.98003, 39.93865, 39.97195, 39.96759, …
$ end_lon             &lt;dbl&gt; -75.14020, -75.14371, -75.16674, -75.13445, -75.17…
$ bike_id             &lt;chr&gt; "03580", "05386", "18082", "02729", "18519", "0272…
$ plan_duration       &lt;dbl&gt; 365, 365, 365, 1, 30, 1, 365, 365, 30, 30, 30, 30,…
$ trip_route_category &lt;chr&gt; "One Way", "One Way", "One Way", "Round Trip", "On…
$ passholder_type     &lt;chr&gt; "Indego365", "Indego365", "Indego365", "Walk-up", …
$ bike_type           &lt;chr&gt; "standard", "standard", "electric", "standard", "e…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(indego)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "trip_id"             "duration"            "start_time"         
 [4] "end_time"            "start_station"       "start_lat"          
 [7] "start_lon"           "end_station"         "end_lat"            
[10] "end_lon"             "bike_id"             "plan_duration"      
[13] "trip_route_category" "passholder_type"     "bike_type"          </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>indego <span class="ot">&lt;-</span> indego <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Parse datetime</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_datetime =</span> <span class="fu">mdy_hm</span>(start_time),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">end_datetime   =</span> <span class="fu">mdy_hm</span>(end_time),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create hourly bins</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">interval60 =</span> <span class="fu">floor_date</span>(start_datetime, <span class="at">unit =</span> <span class="st">"hour"</span>),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Time features</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">week  =</span> <span class="fu">week</span>(interval60),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw  =</span> <span class="fu">wday</span>(interval60, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour  =</span> <span class="fu">hour</span>(interval60),</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">date  =</span> <span class="fu">as.Date</span>(interval60)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick check</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(indego)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 299,121
Columns: 22
$ trip_id             &lt;dbl&gt; 1050296434, 1050293063, 1050296229, 1050276817, 10…
$ duration            &lt;dbl&gt; 22, 8, 12, 1, 5, 9, 5, 6, 16, 16, 16, 39, 6, 40, 1…
$ start_time          &lt;chr&gt; "10/1/2024 0:00", "10/1/2024 0:06", "10/1/2024 0:0…
$ end_time            &lt;chr&gt; "10/1/2024 0:22", "10/1/2024 0:14", "10/1/2024 0:1…
$ start_station       &lt;dbl&gt; 3322, 3166, 3007, 3166, 3075, 3166, 3030, 3010, 33…
$ start_lat           &lt;dbl&gt; 39.93638, 39.97195, 39.94517, 39.97195, 39.96718, …
$ start_lon           &lt;dbl&gt; -75.15526, -75.13445, -75.15993, -75.13445, -75.16…
$ end_station         &lt;dbl&gt; 3375, 3017, 3244, 3166, 3102, 3008, 3203, 3163, 33…
$ end_lat             &lt;dbl&gt; 39.96036, 39.98003, 39.93865, 39.97195, 39.96759, …
$ end_lon             &lt;dbl&gt; -75.14020, -75.14371, -75.16674, -75.13445, -75.17…
$ bike_id             &lt;chr&gt; "03580", "05386", "18082", "02729", "18519", "0272…
$ plan_duration       &lt;dbl&gt; 365, 365, 365, 1, 30, 1, 365, 365, 30, 30, 30, 30,…
$ trip_route_category &lt;chr&gt; "One Way", "One Way", "One Way", "Round Trip", "On…
$ passholder_type     &lt;chr&gt; "Indego365", "Indego365", "Indego365", "Walk-up", …
$ bike_type           &lt;chr&gt; "standard", "standard", "electric", "standard", "e…
$ start_datetime      &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 00:06:00, 2024-10…
$ end_datetime        &lt;dttm&gt; 2024-10-01 00:22:00, 2024-10-01 00:14:00, 2024-10…
$ interval60          &lt;dttm&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2…
$ week                &lt;dbl&gt; 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40…
$ dotw                &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, …
$ hour                &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ date                &lt;date&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2…</code></pre>
</div>
</div>
<p><strong>Next, we converted the trip start and end times to proper datetime objects and binned each trip into an hourly interval (interval60). I also created standard temporal features: week number, day of week, hour of day, and calendar date. These fields form the backbone of the time-series modeling</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>trips_panel <span class="ot">&lt;-</span> indego <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    interval60,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    start_station,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    start_lat,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    start_lon</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Trip_Count =</span> <span class="fu">n</span>(),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(trips_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 158,517
Columns: 5
$ interval60    &lt;dttm&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2024-10…
$ start_station &lt;dbl&gt; 3007, 3008, 3010, 3025, 3030, 3033, 3041, 3075, 3097, 30…
$ start_lat     &lt;dbl&gt; 39.94517, 39.98081, 39.94711, 39.93724, 39.93935, 39.950…
$ start_lon     &lt;dbl&gt; -75.15993, -75.15067, -75.16618, -75.16120, -75.15716, -…
$ Trip_Count    &lt;int&gt; 3, 1, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1,…</code></pre>
</div>
</div>
<p><strong>I aggregated the raw trip records into a station–hour panel. For each combination of starting station, hour, and location (lat/lon), I counted the number of trips (Trip_Count). This reduces the data from individual trips to a count outcome suitable for demand modelin</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many unique stations and hours do we have?</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>n_stations <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(trips_panel<span class="sc">$</span>start_station))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>n_hours    <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(trips_panel<span class="sc">$</span>interval60))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>n_stations</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 256</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>n_hours</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2208</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How many rows would a complete panel have?</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>expected_rows <span class="ot">&lt;-</span> n_stations <span class="sc">*</span> n_hours</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>expected_rows</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 565248</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the full station-hour grid</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>study_panel <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval60    =</span> <span class="fu">sort</span>(<span class="fu">unique</span>(trips_panel<span class="sc">$</span>interval60)),</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">start_station =</span> <span class="fu">sort</span>(<span class="fu">unique</span>(trips_panel<span class="sc">$</span>start_station))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Bring in the observed trip counts + lat/lon</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(trips_panel, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"interval60"</span>, <span class="st">"start_station"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Any missing Trip_Count means 0 trips in that hour at that station</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">Trip_Count =</span> <span class="fu">replace_na</span>(Trip_Count, <span class="dv">0</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 565,248
Columns: 5
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ start_lat     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ start_lon     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build station attributes (one row per station)</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>station_attributes <span class="ot">&lt;-</span> trips_panel <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lat =</span> <span class="fu">first</span>(start_lat),</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">start_lon =</span> <span class="fu">first</span>(start_lon),</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(station_attributes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 256
Columns: 3
$ start_station &lt;dbl&gt; 3000, 3005, 3006, 3007, 3008, 3009, 3010, 3012, 3014, 30…
$ start_lat     &lt;dbl&gt; 39.91591, 39.94733, 39.95220, 39.94517, 39.98081, 39.955…
$ start_lon     &lt;dbl&gt; -75.18370, -75.14403, -75.20311, -75.15993, -75.15067, -…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the mostly-NA lat/lon columns, then join clean ones back</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>study_panel <span class="ot">&lt;-</span> study_panel <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>start_lat, <span class="sc">-</span>start_lon) <span class="sc">%&gt;%</span>   <span class="co"># drop old ones</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(station_attributes, <span class="at">by =</span> <span class="st">"start_station"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 565,248
Columns: 5
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ start_lat     &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.915…
$ start_lon     &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75.18…</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>study_panel <span class="ot">&lt;-</span> study_panel <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">week    =</span> <span class="fu">week</span>(interval60),</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month   =</span> <span class="fu">month</span>(interval60, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw    =</span> <span class="fu">wday</span>(interval60, <span class="at">label =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">hour    =</span> <span class="fu">hour</span>(interval60),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">date    =</span> <span class="fu">as.Date</span>(interval60),</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekend =</span> <span class="fu">ifelse</span>(dotw <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sat"</span>, <span class="st">"Sun"</span>), <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">rush_hour =</span> <span class="fu">ifelse</span>(hour <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">16</span>, <span class="dv">17</span>, <span class="dv">18</span>), <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 565,248
Columns: 12
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ start_lat     &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.915…
$ start_lon     &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75.18…
$ week          &lt;dbl&gt; 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, …
$ month         &lt;ord&gt; Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, O…
$ dotw          &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, T…
$ hour          &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16…
$ date          &lt;date&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2024-10…
$ weekend       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ rush_hour     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,…</code></pre>
</div>
</div>
<p><strong>I created a separate station-level table with one record per start_station, storing its latitude and longitude. I then rejoined these attributes back into the full panel so that every station–hour row has consistent, non-missing coordinates for mapping and spatial analysis</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get weather from Philly airport (KPHL) for Q4 2024</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>weather_data <span class="ot">&lt;-</span> <span class="fu">riem_measures</span>(</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">station    =</span> <span class="st">"PHL"</span>,          <span class="co"># Philadelphia International Airport</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">date_start =</span> <span class="st">"2024-10-01"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">date_end   =</span> <span class="st">"2024-12-31"</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Process into hourly summaries</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>weather_panel <span class="ot">&lt;-</span> weather_data <span class="sc">%&gt;%</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">interval60   =</span> <span class="fu">floor_date</span>(valid, <span class="at">unit =</span> <span class="st">"hour"</span>),</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Temperature  =</span> tmpf,                      <span class="co"># temp in F</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">Precipitation =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(p01i), <span class="dv">0</span>, p01i),</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">Wind_Speed   =</span> sknt</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(interval60, Temperature, Precipitation, Wind_Speed) <span class="sc">%&gt;%</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>()</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(weather_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,554
Columns: 4
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ Temperature   &lt;dbl&gt; 67.0, 65.0, 65.0, 65.0, 65.0, 64.0, 64.4, 64.0, 64.4, 64…
$ Precipitation &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Wind_Speed    &lt;dbl&gt; 10, 8, 6, 8, 8, 6, 5, 6, 7, 6, 7, 9, 7, 10, 8, 9, 10, 9,…</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weather_panel<span class="sc">$</span>Temperature)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  12.00   41.00   51.00   50.80   60.95   83.00 </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>study_panel <span class="ot">&lt;-</span> study_panel <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(weather_panel, <span class="at">by =</span> <span class="st">"interval60"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in left_join(., weather_panel, by = "interval60"): Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 7 of `x` matches multiple rows in `y`.
ℹ Row 1 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 659,968
Columns: 15
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ start_lat     &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.915…
$ start_lon     &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75.18…
$ week          &lt;dbl&gt; 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, …
$ month         &lt;ord&gt; Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, O…
$ dotw          &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, T…
$ hour          &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 9, 10, 10, 11, 12, 13, …
$ date          &lt;date&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2024-10…
$ weekend       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ rush_hour     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,…
$ Temperature   &lt;dbl&gt; 67.0, 65.0, 65.0, 65.0, 65.0, 64.0, 64.4, 64.0, 64.4, 64…
$ Precipitation &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Wind_Speed    &lt;dbl&gt; 10, 8, 6, 8, 8, 6, 5, 6, 7, 6, 7, 9, 7, 10, 8, 9, 10, 9,…</code></pre>
</div>
</div>
<p><strong>To avoid missing time periods, I constructed a complete grid of all station–hour combinations present in Q4 2024. I joined the observed trip counts onto this grid and set any missing Trip_Count values to zero. This ensures that the model sees both busy and idle hours for each station</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>study_panel <span class="ot">&lt;-</span> study_panel <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(start_station, interval60) <span class="sc">%&gt;%</span>   <span class="co"># sort correctly</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag1Hour   =</span> <span class="fu">lag</span>(Trip_Count, <span class="dv">1</span>),</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag2Hours  =</span> <span class="fu">lag</span>(Trip_Count, <span class="dv">2</span>),</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag3Hours  =</span> <span class="fu">lag</span>(Trip_Count, <span class="dv">3</span>),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag12Hours =</span> <span class="fu">lag</span>(Trip_Count, <span class="dv">12</span>),</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag1day    =</span> <span class="fu">lag</span>(Trip_Count, <span class="dv">24</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 659,968
Columns: 20
$ interval60    &lt;dttm&gt; 2024-10-01 00:00:00, 2024-10-01 01:00:00, 2024-10-01 02…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ start_lat     &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.915…
$ start_lon     &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75.18…
$ week          &lt;dbl&gt; 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, …
$ month         &lt;ord&gt; Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, O…
$ dotw          &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, Tue, T…
$ hour          &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 9, 10, 10, 11, 12, 13, …
$ date          &lt;date&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2024-10…
$ weekend       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ rush_hour     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,…
$ Temperature   &lt;dbl&gt; 67.0, 65.0, 65.0, 65.0, 65.0, 64.0, 64.4, 64.0, 64.4, 64…
$ Precipitation &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Wind_Speed    &lt;dbl&gt; 10, 8, 6, 8, 8, 6, 5, 6, 7, 6, 7, 9, 7, 10, 8, 9, 10, 9,…
$ lag1Hour      &lt;int&gt; NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ lag2Hours     &lt;int&gt; NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ lag3Hours     &lt;int&gt; NA, NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag12Hours    &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0, 0, 0,…
$ lag1day       &lt;int&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …</code></pre>
</div>
</div>
<p><strong>To capture persistence in demand, I created several lagged features for each station: trips 1, 2, and 3 hours ago, 12 hours ago, and 24 hours ago (lag1day). These lags help the model learn that current demand often depends on recent demand at the same station</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>study_panel_complete <span class="ot">&lt;-</span> study_panel <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(lag1Hour),</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(lag2Hours),</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(lag3Hours),</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(lag12Hours),</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    <span class="sc">!</span><span class="fu">is.na</span>(lag1day)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(study_panel_complete)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 653,824
Columns: 20
$ interval60    &lt;dttm&gt; 2024-10-01 18:00:00, 2024-10-01 19:00:00, 2024-10-01 20…
$ start_station &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 30…
$ Trip_Count    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ start_lat     &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.915…
$ start_lon     &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75.18…
$ week          &lt;dbl&gt; 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, …
$ month         &lt;ord&gt; Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, Oct, O…
$ dotw          &lt;ord&gt; Tue, Tue, Tue, Tue, Tue, Tue, Wed, Wed, Wed, Wed, Wed, W…
$ hour          &lt;int&gt; 18, 19, 20, 21, 22, 23, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10…
$ date          &lt;date&gt; 2024-10-01, 2024-10-01, 2024-10-01, 2024-10-01, 2024-10…
$ weekend       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ rush_hour     &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,…
$ Temperature   &lt;dbl&gt; 73, 71, 70, 68, 67, 65, 64, 64, 63, 62, 62, 63, 63, 62, …
$ Precipitation &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ Wind_Speed    &lt;dbl&gt; 13, 10, 11, 9, 12, 9, 9, 8, 6, 6, 7, 7, 7, 5, 8, 7, 6, 6…
$ lag1Hour      &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag2Hours     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag3Hours     &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag12Hours    &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag1day       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…</code></pre>
</div>
</div>
<p><strong>Because lagged variables are undefined for the first few hours at each station, I removed rows with missing lag values. The resulting study_panel_complete starts after the first full day of data and has all lag features populated, which is necessary for modeling</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Temporal train/test split for Q4 2024</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(week <span class="sc">&lt;</span> <span class="dv">50</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(week <span class="sc">&gt;=</span> <span class="dv">50</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic checks</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 461056</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 192768</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(train<span class="sc">$</span>date); <span class="fu">max</span>(train<span class="sc">$</span>date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2024-10-01"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2024-12-08"</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(test<span class="sc">$</span>date);  <span class="fu">max</span>(test<span class="sc">$</span>date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2024-12-09"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "2024-12-31"</code></pre>
</div>
</div>
</section>
<section id="model-creation" class="level3">
<h3 class="anchored" data-anchor-id="model-creation">Model Creation</h3>
<p><strong>I split the data into a training set (weeks 40–49) and a test set (weeks 50–52). This temporal split avoids leaking future information into the past and mimics a real-world forecasting scenario where we train on earlier weeks and evaluate on later weeks in the same quarter</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># In the training data: make a clean day-of-week factor</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw_simple =</span> <span class="fu">factor</span>(</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>      dotw,</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Set dummy (treatment) coding for dotw_simple</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(train<span class="sc">$</span>dotw_simple) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">7</span>)</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick check</span></span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>dotw_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
  Mon   Tue   Wed   Thu   Fri   Sat   Sun 
61952 62976 63488 78848 65536 66048 62208 </code></pre>
</div>
</div>
<p><strong>In the training data, I created a clean day-of-week factor (dotw_simple) with an explicit ordering from Monday to Sunday and set treatment/dummy coding. This makes the interpretation of day-of-week coefficients more straightforward in the linear model</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  Trip_Count <span class="sc">~</span> </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(hour) <span class="sc">+</span>        <span class="co"># hour of day</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>    dotw_simple <span class="sc">+</span>            <span class="co"># day of week</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>    Temperature <span class="sc">+</span> </span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>    Precipitation,</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + 
    Precipitation, data = train)

Residuals:
   Min     1Q Median     3Q    Max 
-1.711 -0.664 -0.224  0.170 41.412 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -0.4879190  0.0132141 -36.924  &lt; 2e-16 ***
as.factor(hour)1  -0.0502730  0.0124199  -4.048 5.17e-05 ***
as.factor(hour)2  -0.0721180  0.0122118  -5.906 3.52e-09 ***
as.factor(hour)3  -0.1028604  0.0121784  -8.446  &lt; 2e-16 ***
as.factor(hour)4  -0.0676706  0.0120927  -5.596 2.19e-08 ***
as.factor(hour)5   0.0366964  0.0121475   3.021  0.00252 ** 
as.factor(hour)6   0.2733507  0.0121635  22.473  &lt; 2e-16 ***
as.factor(hour)7   0.5347557  0.0123694  43.232  &lt; 2e-16 ***
as.factor(hour)8   0.8718939  0.0121281  71.890  &lt; 2e-16 ***
as.factor(hour)9   0.6413455  0.0122134  52.512  &lt; 2e-16 ***
as.factor(hour)10  0.5390424  0.0120547  44.716  &lt; 2e-16 ***
as.factor(hour)11  0.5738945  0.0120656  47.565  &lt; 2e-16 ***
as.factor(hour)12  0.6673419  0.0119663  55.768  &lt; 2e-16 ***
as.factor(hour)13  0.6486852  0.0118736  54.633  &lt; 2e-16 ***
as.factor(hour)14  0.6664187  0.0119192  55.911  &lt; 2e-16 ***
as.factor(hour)15  0.8001032  0.0122984  65.058  &lt; 2e-16 ***
as.factor(hour)16  0.9396023  0.0120761  77.807  &lt; 2e-16 ***
as.factor(hour)17  1.1311420  0.0121626  93.001  &lt; 2e-16 ***
as.factor(hour)18  0.8160769  0.0122484  66.627  &lt; 2e-16 ***
as.factor(hour)19  0.5285249  0.0122872  43.014  &lt; 2e-16 ***
as.factor(hour)20  0.3154833  0.0123740  25.496  &lt; 2e-16 ***
as.factor(hour)21  0.2157332  0.0123962  17.403  &lt; 2e-16 ***
as.factor(hour)22  0.1643289  0.0123370  13.320  &lt; 2e-16 ***
as.factor(hour)23  0.0747512  0.0124199   6.019 1.76e-09 ***
dotw_simple2       0.0608134  0.0066102   9.200  &lt; 2e-16 ***
dotw_simple3       0.0603034  0.0065983   9.139  &lt; 2e-16 ***
dotw_simple4      -0.0502359  0.0063232  -7.945 1.95e-15 ***
dotw_simple5      -0.0138822  0.0065752  -2.111  0.03475 *  
dotw_simple6      -0.0341312  0.0065498  -5.211 1.88e-07 ***
dotw_simple7      -0.0525136  0.0066632  -7.881 3.25e-15 ***
Temperature        0.0122837  0.0001549  79.281  &lt; 2e-16 ***
Precipitation     -1.0872688  0.0787122 -13.813  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.167 on 461024 degrees of freedom
Multiple R-squared:  0.1082,    Adjusted R-squared:  0.1081 
F-statistic:  1804 on 31 and 461024 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Model 1 is a baseline linear regression that predicts trips per station-hour using only time-of-day, day-of-week, temperature, and precipitation. This captures broad temporal and weather patterns without using any station-specific or lagged information</strong></p>
<p><strong>Model 2 extends the baseline by adding lagged demand features: trips 1 hour ago, 3 hours ago, and 24 hours ago. These lags allow the model to use recent station history to refine predictions, capturing short-run momentum or inertia in bike demand</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span> <span class="fu">filter</span>(week <span class="sc">&lt;</span> <span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "interval60"    "start_station" "Trip_Count"    "start_lat"    
 [5] "start_lon"     "week"          "month"         "dotw"         
 [9] "hour"          "date"          "weekend"       "rush_hour"    
[13] "Temperature"   "Precipitation" "Wind_Speed"    "lag1Hour"     
[17] "lag2Hours"     "lag3Hours"     "lag12Hours"    "lag1day"      </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Trip_Count ~ hour + dotw_simple + Temperature + Precipitation +</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   lag1Hour + lag3Hours + lag1day</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure train has the dotw_simple factor</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(week <span class="sc">&lt;</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw_simple =</span> <span class="fu">factor</span>(</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>      dotw,</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(train<span class="sc">$</span>dotw_simple) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">7</span>)</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Model 2: add lag variables ----</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>  Trip_Count <span class="sc">~</span> </span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(hour) <span class="sc">+</span></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a>    dotw_simple <span class="sc">+</span></span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>    Temperature <span class="sc">+</span></span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a>    Precipitation <span class="sc">+</span></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a>    lag1Hour <span class="sc">+</span></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>    lag3Hours <span class="sc">+</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a>    lag1day,</span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train</span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + 
    Precipitation + lag1Hour + lag3Hours + lag1day, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.599  -0.447  -0.118   0.095  32.952 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -0.1810617  0.0113721 -15.922  &lt; 2e-16 ***
as.factor(hour)1  -0.0133533  0.0106606  -1.253 0.210356    
as.factor(hour)2  -0.0062801  0.0104845  -0.599 0.549183    
as.factor(hour)3  -0.0281245  0.0104592  -2.689 0.007167 ** 
as.factor(hour)4  -0.0033135  0.0103894  -0.319 0.749777    
as.factor(hour)5   0.0560036  0.0104446   5.362 8.24e-08 ***
as.factor(hour)6   0.2334064  0.0104667  22.300  &lt; 2e-16 ***
as.factor(hour)7   0.3798211  0.0106563  35.643  &lt; 2e-16 ***
as.factor(hour)8   0.5790912  0.0104691  55.314  &lt; 2e-16 ***
as.factor(hour)9   0.2355823  0.0105440  22.343  &lt; 2e-16 ***
as.factor(hour)10  0.1905111  0.0103843  18.346  &lt; 2e-16 ***
as.factor(hour)11  0.2305205  0.0103988  22.168  &lt; 2e-16 ***
as.factor(hour)12  0.3284782  0.0103097  31.861  &lt; 2e-16 ***
as.factor(hour)13  0.3003943  0.0102326  29.357  &lt; 2e-16 ***
as.factor(hour)14  0.3269017  0.0102687  31.835  &lt; 2e-16 ***
as.factor(hour)15  0.4282957  0.0106001  40.405  &lt; 2e-16 ***
as.factor(hour)16  0.5175740  0.0104224  49.660  &lt; 2e-16 ***
as.factor(hour)17  0.6247796  0.0105182  59.400  &lt; 2e-16 ***
as.factor(hour)18  0.2804317  0.0105993  26.458  &lt; 2e-16 ***
as.factor(hour)19  0.1344979  0.0105990  12.690  &lt; 2e-16 ***
as.factor(hour)20  0.0164061  0.0106779   1.536 0.124429    
as.factor(hour)21  0.0376574  0.0106632   3.532 0.000413 ***
as.factor(hour)22  0.0538449  0.0105956   5.082 3.74e-07 ***
as.factor(hour)23  0.0192831  0.0106611   1.809 0.070494 .  
dotw_simple2       0.0027613  0.0056761   0.486 0.626627    
dotw_simple3      -0.0167901  0.0056712  -2.961 0.003070 ** 
dotw_simple4      -0.0440361  0.0054285  -8.112 4.99e-16 ***
dotw_simple5      -0.0442213  0.0056486  -7.829 4.94e-15 ***
dotw_simple6      -0.0420728  0.0056238  -7.481 7.38e-14 ***
dotw_simple7      -0.0577401  0.0057222 -10.091  &lt; 2e-16 ***
Temperature        0.0036953  0.0001348  27.407  &lt; 2e-16 ***
Precipitation     -0.9640625  0.0676200 -14.257  &lt; 2e-16 ***
lag1Hour           0.3430462  0.0013896 246.864  &lt; 2e-16 ***
lag3Hours          0.1132067  0.0013535  83.641  &lt; 2e-16 ***
lag1day            0.2125180  0.0012972 163.826  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.002 on 461021 degrees of freedom
Multiple R-squared:  0.343, Adjusted R-squared:  0.343 
F-statistic:  7080 on 34 and 461021 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  Trip_Count <span class="sc">~</span> </span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(hour) <span class="sc">+</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>    dotw_simple <span class="sc">+</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>    Temperature <span class="sc">+</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>    Precipitation <span class="sc">+</span></span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>    lag1Hour <span class="sc">+</span></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>    lag3Hours <span class="sc">+</span></span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>    lag1day <span class="sc">+</span></span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(start_station),</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train</span>
<span id="cb66-12"><a href="#cb66-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb66-13"><a href="#cb66-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-14"><a href="#cb66-14" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3677229</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>model5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  Trip_Count <span class="sc">~</span> </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(hour) <span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>    dotw_simple <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>    Temperature <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>    Precipitation <span class="sc">+</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>    lag1Hour <span class="sc">+</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>    lag3Hours <span class="sc">+</span></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>    lag1day <span class="sc">+</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(start_station) <span class="sc">+</span></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>    rush_hour <span class="sc">*</span> weekend,   <span class="co"># interaction term</span></span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train</span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model5)<span class="sc">$</span>adj.r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3710861</code></pre>
</div>
</div>
<p><strong>Model 4 adds station fixed effects via as.factor(start_station). This lets each station have its own baseline level of demand, controlling for unobserved factors like land use, nearby transit, or neighborhood characteristics that are constant over time within the quarter</strong></p>
<p><strong>Model 5 keeps the station fixed effects and lag structure and adds an interaction between rush_hour and weekend. This allows the effect of rush-hour periods to differ between weekdays and weekends, reflecting the idea that commuting peaks may be weaker or absent on weekends</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recreate dotw_simple inside test</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw_simple =</span> <span class="fu">factor</span>(</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>      dotw,</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(test<span class="sc">$</span>dotw_simple) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">7</span>)</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predictions</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred1 =</span> <span class="fu">predict</span>(model1, <span class="at">newdata =</span> test),</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred2 =</span> <span class="fu">predict</span>(model2, <span class="at">newdata =</span> test),</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred4 =</span> <span class="fu">predict</span>(model4, <span class="at">newdata =</span> test),</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred5 =</span> <span class="fu">predict</span>(model5, <span class="at">newdata =</span> test)</span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There were 4 warnings in `mutate()`.
The first warning was:
ℹ In argument: `pred1 = predict(model1, newdata = test)`.
Caused by warning:
! contrasts dropped from factor dotw_simple
ℹ Run `dplyr::last_dplyr_warnings()` to see the 3 remaining warnings.</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 25
  interval60          start_station Trip_Count start_lat start_lon  week month
  &lt;dttm&gt;                      &lt;dbl&gt;      &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;ord&gt;
1 2024-12-09 00:00:00          3000          0      39.9     -75.2    50 Dec  
2 2024-12-09 01:00:00          3000          0      39.9     -75.2    50 Dec  
3 2024-12-09 02:00:00          3000          0      39.9     -75.2    50 Dec  
4 2024-12-09 03:00:00          3000          0      39.9     -75.2    50 Dec  
5 2024-12-09 04:00:00          3000          0      39.9     -75.2    50 Dec  
6 2024-12-09 05:00:00          3000          0      39.9     -75.2    50 Dec  
# ℹ 18 more variables: dotw &lt;ord&gt;, hour &lt;int&gt;, date &lt;date&gt;, weekend &lt;dbl&gt;,
#   rush_hour &lt;dbl&gt;, Temperature &lt;dbl&gt;, Precipitation &lt;dbl&gt;, Wind_Speed &lt;dbl&gt;,
#   lag1Hour &lt;int&gt;, lag2Hours &lt;int&gt;, lag3Hours &lt;int&gt;, lag12Hours &lt;int&gt;,
#   lag1day &lt;int&gt;, dotw_simple &lt;ord&gt;, pred1 &lt;dbl&gt;, pred2 &lt;dbl&gt;, pred4 &lt;dbl&gt;,
#   pred5 &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>I recreated the same day-of-week factor in the test set to match the training coding and then generated out-of-sample predictions from all four models (1, 2, 4, and 5). These predictions are stored as pred1, pred2, pred4, and pred5 for later error analysis</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>mae_results <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Model =</span> <span class="fu">c</span>(</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model 1: Time + Weather"</span>,</span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model 2: + Lags"</span>,</span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model 4: + Station FE"</span>,</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Model 5: + Interaction"</span></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">MAE =</span> <span class="fu">c</span>(</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Trip_Count <span class="sc">-</span> test<span class="sc">$</span>pred1), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Trip_Count <span class="sc">-</span> test<span class="sc">$</span>pred2), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Trip_Count <span class="sc">-</span> test<span class="sc">$</span>pred4), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb74-12"><a href="#cb74-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Trip_Count <span class="sc">-</span> test<span class="sc">$</span>pred5), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb74-13"><a href="#cb74-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb74-14"><a href="#cb74-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb74-15"><a href="#cb74-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-16"><a href="#cb74-16" aria-hidden="true" tabindex="-1"></a>mae_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  Model                     MAE
  &lt;chr&gt;                   &lt;dbl&gt;
1 Model 1: Time + Weather 0.529
2 Model 2: + Lags         0.386
3 Model 4: + Station FE   0.426
4 Model 5: + Interaction  0.428</code></pre>
</div>
</div>
</section>
<section id="mae-and-result-comparison" class="level3">
<h3 class="anchored" data-anchor-id="mae-and-result-comparison">MAE and Result Comparison</h3>
<p><strong>I evaluated each model’s predictive performance on the test weeks using mean absolute error (MAE) in trips per station-hour. Model 2 (with lags) achieved the lowest MAE, while the more complex models with station fixed effects and interactions did not further reduce test error, suggesting some overfitting.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">error_model2 =</span> Trip_Count <span class="sc">-</span> pred2,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">abs_error_model2 =</span> <span class="fu">abs</span>(error_model2),</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">time_of_day =</span> <span class="fu">case_when</span>(</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>      hour <span class="sc">&lt;</span> <span class="dv">7</span> <span class="sc">~</span> <span class="st">"Overnight"</span>,</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>      hour <span class="sc">&gt;=</span> <span class="dv">7</span> <span class="sc">&amp;</span> hour <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">"AM Rush"</span>,</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>      hour <span class="sc">&gt;=</span> <span class="dv">10</span> <span class="sc">&amp;</span> hour <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">"Mid-Day"</span>,</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>      hour <span class="sc">&gt;=</span> <span class="dv">15</span> <span class="sc">&amp;</span> hour <span class="sc">&lt;=</span> <span class="dv">18</span> <span class="sc">~</span> <span class="st">"PM Rush"</span>,</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Evening"</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekend_label =</span> <span class="fu">ifelse</span>(weekend <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"Weekend"</span>, <span class="st">"Weekday"</span>)</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 192,768
Columns: 29
$ interval60       &lt;dttm&gt; 2024-12-09 00:00:00, 2024-12-09 01:00:00, 2024-12-09…
$ start_station    &lt;dbl&gt; 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000,…
$ Trip_Count       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,…
$ start_lat        &lt;dbl&gt; 39.91591, 39.91591, 39.91591, 39.91591, 39.91591, 39.…
$ start_lon        &lt;dbl&gt; -75.1837, -75.1837, -75.1837, -75.1837, -75.1837, -75…
$ week             &lt;dbl&gt; 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 5…
$ month            &lt;ord&gt; Dec, Dec, Dec, Dec, Dec, Dec, Dec, Dec, Dec, Dec, Dec…
$ dotw             &lt;ord&gt; Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon…
$ hour             &lt;int&gt; 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 10, 11, 12, 13, …
$ date             &lt;date&gt; 2024-12-09, 2024-12-09, 2024-12-09, 2024-12-09, 2024…
$ weekend          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ rush_hour        &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,…
$ Temperature      &lt;dbl&gt; 53.0, 47.0, 46.0, 40.0, 41.0, 39.0, 38.0, 35.0, 38.0,…
$ Precipitation    &lt;dbl&gt; 0e+00, 0e+00, 0e+00, 0e+00, 0e+00, 0e+00, 0e+00, 0e+0…
$ Wind_Speed       &lt;dbl&gt; 5, 4, 3, 0, 3, 3, 3, 0, 0, 0, 6, 0, 4, 0, 4, 0, 3, 3,…
$ lag1Hour         &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,…
$ lag2Hours        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,…
$ lag3Hours        &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag12Hours       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ lag1day          &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ dotw_simple      &lt;ord&gt; Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon, Mon…
$ pred1            &lt;dbl&gt; 0.163116969, 0.039141761, 0.005013041, -0.099431449, …
$ pred2            &lt;dbl&gt; 0.01478892, -0.02073618, -0.01735821, -0.06137443, -0…
$ pred4            &lt;dbl&gt; -0.233794952, -0.289921904, -0.296658732, -0.35659619…
$ pred5            &lt;dbl&gt; -0.26141249, -0.31992072, -0.32622711, -0.38540208, -…
$ error_model2     &lt;dbl&gt; -0.01478892, 0.02073618, 0.01735821, 0.06137443, 0.03…
$ abs_error_model2 &lt;dbl&gt; 0.01478892, 0.02073618, 0.01735821, 0.06137443, 0.032…
$ time_of_day      &lt;chr&gt; "Overnight", "Overnight", "Overnight", "Overnight", "…
$ weekend_label    &lt;chr&gt; "Weekday", "Weekday", "Weekday", "Weekday", "Weekday"…</code></pre>
</div>
</div>
<p><strong>Focusing on Model 2 (the best-performing model), I computed residuals (error_model2) and absolute errors (abs_error_model2) for each station-hour in the test set. I also grouped hours into broader time-of-day buckets (Overnight, AM Rush, Mid-Day, PM Rush, Evening) and labeled each record as Weekend or Weekday to study temporal error patterns</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(test, <span class="fu">aes</span>(<span class="at">x =</span> Trip_Count, <span class="at">y =</span> pred2)) <span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.15</span>, <span class="at">color =</span> <span class="st">"#3182bd"</span>) <span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(weekend_label <span class="sc">~</span> time_of_day) <span class="sc">+</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Observed vs. Predicted Trips (Model 2)"</span>,</span>
<span id="cb78-10"><a href="#cb78-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Faceted by Weekend/Weekday and Time of Day"</span>,</span>
<span id="cb78-11"><a href="#cb78-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Observed Trips"</span>,</span>
<span id="cb78-12"><a href="#cb78-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Trips"</span></span>
<span id="cb78-13"><a href="#cb78-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb78-14"><a href="#cb78-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6144 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 6144 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment5_Sen_Sam_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="part-ii-error-analysis" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-error-analysis">Part II: Error Analysis</h2>
<section id="spatial-patterns" class="level3">
<h3 class="anchored" data-anchor-id="spatial-patterns">Spatial Patterns</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>station_errors <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(start_station, start_lat, start_lon) <span class="sc">%&gt;%</span></span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">MAE =</span> <span class="fu">mean</span>(abs_error_model2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb83-5"><a href="#cb83-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_demand =</span> <span class="fu">mean</span>(Trip_Count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb83-6"><a href="#cb83-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb83-7"><a href="#cb83-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb83-8"><a href="#cb83-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-9"><a href="#cb83-9" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(station_errors)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 256
Columns: 5
$ start_station &lt;dbl&gt; 3000, 3005, 3006, 3007, 3008, 3009, 3010, 3012, 3014, 30…
$ start_lat     &lt;dbl&gt; 39.91591, 39.94733, 39.95220, 39.94517, 39.98081, 39.955…
$ start_lon     &lt;dbl&gt; -75.18370, -75.14403, -75.20311, -75.15993, -75.15067, -…
$ MAE           &lt;dbl&gt; 0.1969320, 0.4098259, 0.3811196, 0.6119506, 0.3124952, 0…
$ avg_demand    &lt;dbl&gt; 0.01460823, 0.27490040, 0.26826029, 0.69986720, 0.152722…</code></pre>
</div>
</div>
<p><strong>To examine spatial patterns in prediction error, I aggregated the test-set errors to the station level. For each station, I calculated the MAE of Model 2 and the average demand in the test period. This creates a station-level dataset (station_errors) that can be visualized on a map</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">tigris_use_cache =</span> <span class="cn">TRUE</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>philly_boundary <span class="ot">&lt;-</span> <span class="fu">places</span>(</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">state =</span> <span class="st">"PA"</span>,</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">cb =</span> <span class="cn">TRUE</span>,</span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2023</span></span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(NAME <span class="sc">==</span> <span class="st">"Philadelphia"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">4326</span>)   <span class="co"># match lon/lat CRS</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Philly polygon background</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> philly_boundary,</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"grey95"</span>,</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">linewidth =</span> <span class="fl">0.3</span></span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Station error points</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> station_errors,</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> start_lon, <span class="at">y =</span> start_lat, <span class="at">color =</span> MAE),</span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">2</span>,</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.9</span></span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">"plasma"</span>, <span class="at">direction =</span> <span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_sf</span>(<span class="at">expand =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Spatial Distribution of Prediction Errors (Model 2)"</span>,</span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"MAE per Station – Q4 2024"</span>,</span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"MAE"</span></span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text  =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>()</span>
<span id="cb86-28"><a href="#cb86-28" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment5_Sen_Sam_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Finally, I mapped Model 2’s MAE by station using each station’s longitude and latitude. Each point represents a station, colored by its mean absolute error in the test period. This “MAE map” highlights spatial clusters where the model systematically under- or over-performs, which helps identify neighborhoods where additional features or different modeling approaches may be needed.The spatial distribution of Model 2’s prediction errors reveals a clear pattern across Philadelphia. The highest MAE values occur in and around Center City and University City, where trip activity is more variable and influenced by commuting, tourism, dining, and university schedules. These areas experience sharper peaks and dips in demand, making them more difficult to predict using time, weather, and lag-based features alone.In contrast, lower MAE values appear in many outer neighborhoods such as South Philly, Northwest Philly, and parts of West Philly, where trip volumes tend to be more stable, dominated by routine local travel, or close to zero during many hours. Because these stations have more consistent patterns—or are often inactive—the model performs more accurately.Overall, the map suggests that high-activity, mixed-use areas create the greatest forecasting challenges, while residential or low-activity neighborhoods yield more predictable, lower-error demand patterns. This spatial clustering of errors points to potential opportunities for feature engineering focused on employment centers, universities, and event-driven stations</strong></p>
</section>
<section id="temporal-patterns" class="level3">
<h3 class="anchored" data-anchor-id="temporal-patterns">Temporal Patterns</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>temporal_errors <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(time_of_day, weekend_label) <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">MAE =</span> <span class="fu">mean</span>(abs_error_model2, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(temporal_errors, <span class="fu">aes</span>(<span class="at">x =</span> time_of_day, <span class="at">y =</span> MAE, <span class="at">fill =</span> weekend_label)) <span class="sc">+</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Weekday"</span> <span class="ot">=</span> <span class="st">"#08519c"</span>, <span class="st">"Weekend"</span> <span class="ot">=</span> <span class="st">"#6baed6"</span>)) <span class="sc">+</span></span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Temporal Error Patterns (Model 2)"</span>,</span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"MAE by Time of Day and Weekday/Weekend"</span>,</span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Time of Day"</span>,</span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Absolute Error"</span>,</span>
<span id="cb87-16"><a href="#cb87-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Day Type"</span></span>
<span id="cb87-17"><a href="#cb87-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb87-18"><a href="#cb87-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb87-19"><a href="#cb87-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Assignment5_Sen_Sam_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>The temporal error analysis shows that Model 2 performs unevenly across different times of day. Prediction errors are highest during the AM and PM rush periods, particularly on weekdays, when commuting patterns create sharp spikes in demand that are harder for the model to capture. Mid-day and evening periods show moderate error levels, reflecting more stable leisure and errand travel.Overnight hours have the lowest errors for both weekdays and weekends because most stations have near-zero demand during this period, making predictions easier. The fact that weekend rush periods exhibit lower MAE than weekday rush periods suggests that weekend bike usage is less peaky, more uniform, and therefore easier to forecast. Overall, the model struggles most during high-volume, high-variability commuting hours.</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>study_panel_complete <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Feature 1: Feels-like temperature</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">feels_like =</span> Temperature <span class="sc">-</span> <span class="fl">0.1</span> <span class="sc">*</span> Wind_Speed,</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Feature 2: Nice-weather indicator</span></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">nice_weather =</span> <span class="fu">ifelse</span>(Temperature <span class="sc">&gt;=</span> <span class="dv">50</span> <span class="sc">&amp;</span> Precipitation <span class="sc">==</span> <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(week <span class="sc">&lt;</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw_simple =</span> <span class="fu">factor</span>(</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>      dotw,</span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>)</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(train<span class="sc">$</span>dotw_simple) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">7</span>)</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> study_panel_complete <span class="sc">%&gt;%</span></span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(week <span class="sc">&gt;=</span> <span class="dv">50</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">dotw_simple =</span> <span class="fu">factor</span>(</span>
<span id="cb89-16"><a href="#cb89-16" aria-hidden="true" tabindex="-1"></a>      dotw,</span>
<span id="cb89-17"><a href="#cb89-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Mon"</span>, <span class="st">"Tue"</span>, <span class="st">"Wed"</span>, <span class="st">"Thu"</span>, <span class="st">"Fri"</span>, <span class="st">"Sat"</span>, <span class="st">"Sun"</span>)</span>
<span id="cb89-18"><a href="#cb89-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb89-19"><a href="#cb89-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb89-20"><a href="#cb89-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-21"><a href="#cb89-21" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(test<span class="sc">$</span>dotw_simple) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">7</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>model6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  Trip_Count <span class="sc">~</span> </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">as.factor</span>(hour) <span class="sc">+</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>    dotw_simple <span class="sc">+</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>    Temperature <span class="sc">+</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>    Precipitation <span class="sc">+</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>    lag1Hour <span class="sc">+</span></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>    lag3Hours <span class="sc">+</span></span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>    lag1day <span class="sc">+</span></span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>    feels_like <span class="sc">+</span></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>    nice_weather,</span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train</span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-15"><a href="#cb90-15" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model6)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + 
    Precipitation + lag1Hour + lag3Hours + lag1day + feels_like + 
    nice_weather, data = train)

Residuals:
    Min      1Q  Median      3Q     Max 
-13.574  -0.446  -0.117   0.097  32.974 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -1.513e-01  1.310e-02 -11.551  &lt; 2e-16 ***
as.factor(hour)1  -1.488e-02  1.067e-02  -1.395 0.162887    
as.factor(hour)2  -8.204e-03  1.049e-02  -0.782 0.434191    
as.factor(hour)3  -3.059e-02  1.053e-02  -2.905 0.003667 ** 
as.factor(hour)4  -5.929e-03  1.042e-02  -0.569 0.569289    
as.factor(hour)5   5.213e-02  1.047e-02   4.978 6.44e-07 ***
as.factor(hour)6   2.299e-01  1.050e-02  21.890  &lt; 2e-16 ***
as.factor(hour)7   3.750e-01  1.069e-02  35.082  &lt; 2e-16 ***
as.factor(hour)8   5.741e-01  1.051e-02  54.600  &lt; 2e-16 ***
as.factor(hour)9   2.305e-01  1.059e-02  21.769  &lt; 2e-16 ***
as.factor(hour)10  1.862e-01  1.041e-02  17.875  &lt; 2e-16 ***
as.factor(hour)11  2.263e-01  1.043e-02  21.693  &lt; 2e-16 ***
as.factor(hour)12  3.266e-01  1.033e-02  31.623  &lt; 2e-16 ***
as.factor(hour)13  3.016e-01  1.024e-02  29.455  &lt; 2e-16 ***
as.factor(hour)14  3.309e-01  1.029e-02  32.160  &lt; 2e-16 ***
as.factor(hour)15  4.322e-01  1.062e-02  40.696  &lt; 2e-16 ***
as.factor(hour)16  5.232e-01  1.047e-02  49.992  &lt; 2e-16 ***
as.factor(hour)17  6.333e-01  1.061e-02  59.703  &lt; 2e-16 ***
as.factor(hour)18  2.892e-01  1.069e-02  27.060  &lt; 2e-16 ***
as.factor(hour)19  1.423e-01  1.068e-02  13.330  &lt; 2e-16 ***
as.factor(hour)20  2.303e-02  1.074e-02   2.143 0.032075 *  
as.factor(hour)21  4.095e-02  1.068e-02   3.833 0.000126 ***
as.factor(hour)22  5.448e-02  1.060e-02   5.138 2.77e-07 ***
as.factor(hour)23  1.935e-02  1.066e-02   1.815 0.069601 .  
dotw_simple2       6.808e-04  5.731e-03   0.119 0.905454    
dotw_simple3      -1.967e-02  5.702e-03  -3.451 0.000559 ***
dotw_simple4      -4.134e-02  5.447e-03  -7.589 3.23e-14 ***
dotw_simple5      -4.206e-02  5.659e-03  -7.432 1.07e-13 ***
dotw_simple6      -4.049e-02  5.671e-03  -7.139 9.39e-13 ***
dotw_simple7      -6.072e-02  5.749e-03 -10.562  &lt; 2e-16 ***
Temperature       -1.977e-02  3.526e-03  -5.608 2.04e-08 ***
Precipitation     -9.336e-01  6.865e-02 -13.599  &lt; 2e-16 ***
lag1Hour           3.430e-01  1.390e-03 246.783  &lt; 2e-16 ***
lag3Hours          1.132e-01  1.354e-03  83.589  &lt; 2e-16 ***
lag1day            2.124e-01  1.298e-03 163.698  &lt; 2e-16 ***
feels_like         2.326e-02  3.510e-03   6.627 3.44e-11 ***
nice_weather      -4.963e-05  5.055e-03  -0.010 0.992167    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.002 on 460763 degrees of freedom
  (256 observations deleted due to missingness)
Multiple R-squared:  0.343, Adjusted R-squared:  0.343 
F-statistic:  6683 on 36 and 460763 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">pred6 =</span> <span class="fu">predict</span>(model6, <span class="at">newdata =</span> test)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `pred6 = predict(model6, newdata = test)`.
Caused by warning:
! contrasts dropped from factor dotw_simple</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>mae_model6 <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">abs</span>(test<span class="sc">$</span>Trip_Count <span class="sc">-</span> test<span class="sc">$</span>pred6), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>mae_model6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3869234</code></pre>
</div>
</div>
<p><strong>I added two new weather-based features to Model 2:(1) Feels-like temperature, capturing wind chill effects, and (2) A “nice-weather” indicator for hours with temperature ≥ 50°F and zero precipitation. After refitting the model (Model 6), the resulting MAE on the Q4 2024 test set was 0.3869, virtually the same as Model 2’s MAE of 0.3860. This suggests that in Q4, when most hours are cold and have low, stable demand, these additional features do not meaningfully improve predictive accuracy.In warmer quarters these features might be more effective, but for Q4 they add little explanatory power because weather conditions vary less and demand is low or zero in many station-hours</strong></p>
<p>I added two new weather-based features to Model 2: (1) Feels-like temperature, capturing wind chill effects, and (2) A “nice-weather” indicator for hours with temperature ≥ 50°F and zero precipitation.</p>
<p>After refitting the model (Model 6), the resulting MAE on the Q4 2024 test set was 0.3869, virtually the same as Model 2’s MAE of 0.3860. This suggests that in Q4, when most hours are cold and have low, stable demand, these additional features do not meaningfully improve predictive accuracy.</p>
<p>In warmer quarters these features might be more effective, but for Q4 they add little explanatory power because weather conditions vary less and demand is low or zero in many station-hours.</p>
<hr>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>